### ISSUE TITLE
Bad results when tracking other objects than people

### ISSUE THREAD

**Issue by DoubleRedX** [mikel-brostrom/yolov8_tracking#464]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I am working on a project which needs to track multi objects. These objects are not person, and  the tracking result is not well. So I am considering how can I train the strong sort to track the object (not person)?

**Comment by mikel-brostrom** [comment]
There are many things you should consider before training a new ReID model. Maybe the motion uncertainty is too high and you need to increase

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/cb5b68dae0a43db9828b2ffa3267a9dccef3c3c0/strong_sort/configs/strong_sort.yaml#L5

Maybe your Yolov5 model isn't good enough... A video example would help figuring out what is gong wrong :smile:

**Comment by brucemuller** [comment]
Hi @mikel-brostrom. I have a similar issue. I can't share my video for privacy reasons but it is of children wearing head mounted cameras around the home, largely playing with toys. So the motion can be very erratic. I'm not concerned with the classification being accurate, more interested in the ReID working well. I tried tweaking the above config and used for example:
--strong-sort-weights osnet_x1_0_msmt17.pt --yolo-weights yolov5x.pt --conf-thres 0.2 --agnostic-nms --max-det 40

The best I can do so far is that some objects will have a handful of different IDs which it uses, noisily (e.g. a cup). So perhaps I need to finetune on some household objects/toy data..
The agnostic-nms still outputs classes - is that expected?

Have you any recommendations?

**Comment by mikel-brostrom** [comment]
> children wearing head mounted cameras around the home

I suspect from this that they move around. This is a hot research topic which is not fully solved yet.
StrongSORT will work well for static scenes, the results won't be great if the kids are moving around.

**Comment by brucemuller** [comment]
@mikel-brostrom Thank you for your reply. That's interesting, I see, yes they're almost always in motion :)  Is there another tracker you think would work better for this? I was thinking of trying mmtracker.

**Comment by mikel-brostrom** [comment]
You will see exactly the same issues there :smile:

**Comment by brucemuller** [comment]
Hi @mikel-brostrom Do you know if there's been any recent progress with MOT with strong egomotion?

**Comment by mikel-brostrom** [comment]
You may find OCSORT interesting: https://arxiv.org/abs/2203.14360. To minimize the ego motion effect, some form of camera motion compensation could be added.

**Comment by brucemuller** [comment]
> You may find OCSORT interesting: https://arxiv.org/abs/2203.14360, mostly because it is very robust to non-linear motion and occlusion. To minimize the ego motion effect, some form of camera motion compensation could be added. I think it is a good combo for cases with strong ego motion, some KalmanFilter tuning may be needed as well for your specific case.

Thanks for your thoughts, I'll make a start on that. Have you got any references for how I go about with tuning for the KalmanFilter? The main issue I have is the object ID will usually switch after going out of frame and back in. Some objects may only re appear after a great many frames.

**Comment by mikel-brostrom** [comment]
The classification is part of the object detection paradigm. Without classification it would be more difficult for the model to learn which features are associated to each class. However, if you disregard the classification and only consider  "objectness", the solution would be considered as an class-agnostic. I have not tried out this myself. But I can imagine that this could work for very simple scenarios. Like simply formed objects on uniform background.
