### ISSUE TITLE
Save segments in save_text output

### ISSUE THREAD

**Issue by Abd-elr4hman** [mikel-brostrom/yolov8_tracking#654]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello,
I found this repo super helpful and very straight forward to use!
Thank you for this amazing work on this repo!
 
# My Question:
I want to get the segmentation masks of the tracked object in the output text file. but,
after examining your code repo for a while I came to the conclusion that the track.py file draws and populates save_text file using the boxes from the tracker output. and draws the masks from the yolo model output:
lines to draw mask: [here](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/track.py#L195).
```
# Mask plotting
annotator.masks(
    masks,
    colors=[colors(x, True) for x in det[:, 5]],
    im_gpu=torch.as_tensor(im0, dtype=torch.float16).to(device).permute(2, 0, 1).flip(0).contiguous() /
    255 if retina_masks else im[i]
)
```

lines to draw boxes: [here](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/track.py#L233).
```
if save_txt:
    # to MOT format
    bbox_left = output[0]
    bbox_top = output[1]
    bbox_w = output[2] - output[0]
    bbox_h = output[3] - output[1]
    # Write MOT compliant results to file
    with open(txt_path + '.txt', 'a') as f:
        f.write(('%g ' * 10 + '\n') % (frame_idx + 1, id, bbox_left,  # MOT format
                                       bbox_top, bbox_w, bbox_h, -1, -1, -1, i))

if save_vid or save_crop or show_vid:  # Add bbox to image
    c = int(cls)  # integer class
    id = int(id)  # integer id
    label = None if hide_labels else (f'{id} {names[c]}' if hide_conf else \
        (f'{id} {conf:.2f}' if hide_class else f'{id} {names[c]} {conf:.2f}'))
    color = colors(c, True)
    annotator.box_label(bboxes, label, color=color)

    if save_trajectories and tracking_method == 'strongsort':
        q = output[7]
        tracker_list[i].trajectory(im0, q, color=color)
    if save_crop:
        txt_file_name = txt_file_name if (isinstance(path, list) and len(path) > 1) else ''
        save_one_box(bboxes, imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)
```
If my understanding is correct the output of the tracker is used to:
 1. draw bboxes.   and 
 2. save text file when --save_text is added.

While the yolo model output is used to draw masks...

since my goal is to get an output text file that contains the segments of the tracked objects I thought of maybe trying to match the yolo segments to the trackers output, and then write the matched results to an output text file.

but I've also came to the conclusion that not all object from the detector has to be tracked and for a single video frame, all detected objects will not necessarily have an associated tracking output. (kindly correct me if I'm wrong about this)

do you have any suggestion for me to output a text file that contains segments of tracked object?

thanks in advance!

**Comment by mikel-brostrom** [comment]
> since my goal is to get an output text file that contains the segments of the tracked objects

Do you mean the segmentation mask withing the bounding boxes associated to a track?
Something like this? 

![208322533-7c77afb0-a6a7-4693-b228-054019416bb3](https://user-images.githubusercontent.com/18719680/208523387-eadf8041-1092-4b19-8867-1bf28f61eaf9.png)

**Comment by Abd-elr4hman** [comment]
I mean the segmentation masks, the pixels associated with the non gray area, the pixels that mark the person inside the bounding box. if I am trying to track the person in the photo.

**Comment by mikel-brostrom** [comment]
Aha, I see. This is implemented to some extent here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/b0ea7d11994a92d7e8cea5613ba765c39ab00025/trackers/strong_sort/strong_sort.py#L152

Only that the mask is not saved

**Comment by mikel-brostrom** [comment]
Aha, I see. This is implemented here:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/b0ea7d11994a92d7e8cea5613ba765c39ab00025/trackers/strong_sort/strong_sort.py#L149

Only that the mask is not saved
