### ISSUE TITLE
Tracker losing tracked object after collision

### ISSUE THREAD

**Issue by aqua1907** [mikel-brostrom/yolov8_tracking#667]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello! I need help understanding why StrongSORT losing an object. Any suggestion would be appreciated. Thank you!

![image](https://user-images.githubusercontent.com/43681334/209657073-2dc71d47-2762-411f-be26-bcba99254ac5.png)
1. Reassign tracked object to a newly detected object with the current object_d

![image](https://user-images.githubusercontent.com/43681334/209657147-1e19a5ad-34be-4452-8748-5164b26ad862.png)
2. Losing tracks after collision with another object

3. Although, I have tried to hide behind the wall for a couple of seconds. And after every appearance on the camera tracker assign a new object_id. So person re-id not working well. (I was facing the camera before hiding the wall and appear facing the camera).

**Comment by mikel-brostrom** [comment]
> Reassign tracked object to a newly detected object with the current object_d

The people object detectors provided here are not the best. We do this so that people don't misuse them. You would need to train your own to get better results

> Losing tracks after collision with another object

This can partially be solved by making predictions ahead:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4a0819c5a5f693f9d127011be52dcaa527611ef6/trackers/strong_sort/configs/strong_sort.yaml#L7

some fine-tuning would most certainly be needed as well for optimal performance 

> Although, I have tried to hide behind the wall for a couple of seconds. And after every appearance on the camera tracker assign a new object_id. So person re-id not working well. (I was facing the camera before hiding the wall and appear facing the camera).

This can partially be solved by:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4a0819c5a5f693f9d127011be52dcaa527611ef6/trackers/strong_sort/configs/strong_sort.yaml#L8

some fine-tuning would most certainly be needed as well for optimal performance

**Comment by aqua1907** [comment]
Thank toy for your time and answer. Below is my config that I am using right now:
STRONGSORT:
  ECC: False              # activate camera motion compensation
  MC_LAMBDA: 0.995       # matching with both appearance (1 - MC_LAMBDA) and motion cost
  EMA_ALPHA: 0.9         # updates  appearance  state in  an exponential moving average manner
  MAX_DIST: 0.3         # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.5  # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 3000            # Maximum number of missed misses before a track is deleted
  N_INIT: 4              # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100         # Maximum size of the appearance descriptors gallery
  MAX_UNMATCHED_PREDS: 40
  

> > Reassign tracked object to a newly detected object with the current object_d
> 
> The people object detectors provided here are not the best. We do this so that people don't misuse them. You would need to train your own to get better results
> 
> > Losing tracks after collision with another object
> 
> This can partially be solved by making predictions ahead:
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4a0819c5a5f693f9d127011be52dcaa527611ef6/trackers/strong_sort/configs/strong_sort.yaml#L7
> 
> some fine-tuning would most certainly be needed as well for optimal performance
> 
> > Although, I have tried to hide behind the wall for a couple of seconds. And after every appearance on the camera tracker assign a new object_id. So person re-id not working well. (I was facing the camera before hiding the wall and appear facing the camera).
> 
> This can partially be solved by:
> 
> https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4a0819c5a5f693f9d127011be52dcaa527611ef6/trackers/strong_sort/configs/strong_sort.yaml#L8
> 
> some fine-tuning would most certainly be needed as well for optimal performance

**Comment by fenguan** [comment]
> > 与其他物体碰撞后丢失轨迹
> 
> 这可以通过提前预测来部分解决：
> 
>MAX_UNMATCHED_PREDS
> 
> > 虽然，我试图躲在墙后面几秒钟。每次出现在相机跟踪器上后，分配一个新的object_id。所以人重新ID不能很好地工作。（我在隐藏墙壁之前面对相机，并面对相机出现）。
> 
> 这可以通过以下方式部分解决：
> 
> MAX_AGE

How to set variable MAX_AGE for each id. That is, the longer the person stays, the larger the MAX_AGE.
