### ISSUE TITLE
How to log validation results with tensorboard

### ISSUE THREAD

**Issue by buyi6666** [mikel-brostrom/yolov8_tracking#692]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,
Does it have some ways that can display the process of runing val.py?

![1234](https://user-images.githubusercontent.com/102564895/212510089-af937f2e-d747-4527-af21-c7246cecf2f3.png)

**Comment by mikel-brostrom** [comment]
By display process you mean display progress?

**Comment by buyi6666** [comment]
Sorry, I don't understand the difference between the two words.

I want to show the running process through diagrams, such as `tensorboard`. I used `tensorboard` in the process of target detection training with yolov5.

I wonder if `val.py` can use tensorboard or other tools or instructions to show the process?

**Comment by mikel-brostrom** [comment]
This is not available yet

**Comment by mikel-brostrom** [comment]
This is now available in master @buyi6666. The following metrics are logged at the end of the process: HOTA, MOTA, IDF1
