### ISSUE TITLE
Save Image

### ISSUE THREAD

**Issue by ExoAis** [mikel-brostrom/yolov8_tracking#702]
How to save the result image? I used --save-vid and it saves it as a video which doesn't open. There is no save-img feature.

**Comment by mikel-brostrom** [comment]
It makes not sense to run a tracker on a single image. Choose a stream like your webcam or a youtube clip :smile:

**Comment by ExoAis** [comment]
This might not be directly related to the issue at hand but how can I get bounding box center coordinates? It gives top and left coordinates. I want to get BB center coordinates to convert them to real world coordinates.

Thanks

> It makes not sense to run a tracker on a single image. Choose a stream like your webcam or a youtube clip 😄
