### ISSUE TITLE
tracking methods performance

### ISSUE THREAD

**Issue by syjeon121** [mikel-brostrom/yolov8_tracking#703]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

hi @mikel-brostrom it is very nice repo and it helps me a lot

I'm curious about the approximate performance of the tracking methods in this repo (in terms of speed and tracking accuracy)

when I tested it with one video on the cpu, bytetracker seems to have the fastest speed, and strongsort and bytetracker have similar accuracy

i would be grateful if you could share the approximate performance of these three methods: btyetracker, strongsort and ocsort

**Comment by mikel-brostrom** [comment]
You have some results on MOT16 here: https://github.com/mikel-brostrom/yolov8_tracking/wiki/StrongSORT-vs-BoTSORT-vs-OCSORT

**Comment by syjeon121** [comment]
thanks!
