### ISSUE TITLE
Run track file with TensorRT

### ISSUE THREAD

**Issue by rdrEren** [mikel-brostrom/yolov8_tracking#704]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

I'd like to try track.py files with tensorrt engines so I created yolov8s.engine file from yolo8s.pt via exporter.py that inside of yolov8/engine folder. However I input the engines like that ; python3 track.py --yolo-weights /home/nvidia/Desktop/ultralytics-main/ultralytics/yolo/engine/yolov8s.engine --tracking-method bytetrack , returned  below error.

 File "track.py", line 133, in run
    model.warmup(imgsz=(1 if pt or model.triton else bs, 3, *imgsz))  # warmup
NameError: name 'bs' is not defined

Finally, your track system not compapitble with tensorRT? Why am I getting that error?

**Comment by mikel-brostrom** [comment]
`git pull`, try again. Should be fixed

**Comment by rdrEren** [comment]
I tried and it works, thanks!
