### ISSUE TITLE
How can i use dataframe in yolov8? (for merged Model)

### ISSUE THREAD

**Issue by jeonniga** [mikel-brostrom/yolov8_tracking#706]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

In YOLOv5, I have try like this....
import torch
import pandas as pd 
....
modelA = torch.hub.load()
modelB = torch.hub.load()

df = pd.concat(modelA, modelB)
....

But, Now in YOLOv8.
How can i try way?

I just want to merge model . 

Please help me....

**Comment by mikel-brostrom** [comment]
This is a pure Yolov8 question. Please ask it here: https://github.com/ultralytics/ultralytics/issues
