### ISSUE TITLE
ImageDraw has problems when model.names is replaced with other languages

### ISSUE THREAD

**Issue by caramelpop** [mikel-brostrom/yolov8_tracking#707]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

`Traceback (most recent call last):`
  `File "C:\Users\admin\Desktop\v5deep\track.py", line 348, in <module>`
    `main(opt)`
  `File "C:\Users\admin\Desktop\v5deep\track.py", line 343, in main`
    `run(**vars(opt))`
  `File "C:\Users\admin\anaconda3\envs\v5deep\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context`
    `return func(*args, **kwargs)`
  `File "C:\Users\admin\Desktop\new_v5deep\track.py", line 244, in run`
    `annotator.box_label(bbox, label, color=color)`
  `File "C:\Users\admin\Desktop\v5deep\yolov5\utils\plots.py", line 89, in box_label`
    `self.draw.rectangle(box, width=self.lw, outline=color)  # box`
  `File "C:\Users\admin\anaconda3\envs\v5deep\lib\site-packages\PIL\ImageDraw.py", line 295, in rectangle`
    `self.draw.draw_rectangle(xy, ink, 0, width)`
`TypeError: coordinate list must contain exactly 2 coordinates`

### Minimal Reproducible Example

When I changed model.names in track.py of Yolov5_StrongSORT_OSNet to Korean, I got an error.
When model.names = ['apple' , 'pineapple'], it displays fine.

Also, if I write model.names = ['사과' , '파인애플'] in the same way in yolov5's detect.py, it is displayed without any problem.

`model = DetectMultiBackend(yolo_weights, device=device, dnn=dnn, data=None, fp16=half)`
`model.names = ['사과' , '파인애플']  #['apple' , 'pineapple']`
`stride, names, pt = model.stride, model.names, model.pt`

**Comment by mikel-brostrom** [comment]
This is a pure Yolov8 issue. Please, ask this here: https://github.com/ultralytics/ultralytics/issues

**Comment by caramelpop** [comment]
It runs fine on ultralytics/yolov5.

This is the error I get in track.py on Yolov5_StrongSORT_OSNet.

I think there is a problem with bbox 
 `annotator.box_label(bbox, label, color=color).`

@mikel-brostrom, do you get the error if you define model.names in a different language and run it in your environment?
