### ISSUE TITLE
There's a little bug in mask plotting

### ISSUE THREAD

**Issue by hdnh2006** [mikel-brostrom/yolov8_tracking#708]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

While the boxes and classes are correctly labeled, the masks from keep the color from the first detection the model does.

Take a look at the following image:

![image](https://user-images.githubusercontent.com/17271049/215098497-9137c21a-f43d-459e-a2fd-cadff36dc995.png)

First detection was a car, but clearly it is a truck, however, the segmentation mask keep the car color. 

I'll try to submit a PR.c

**Comment by hdnh2006** [comment]
Hi @mikel-brostrom it seems the problem is bigger than I thought. It seems the tracker is not correctly updating the bounding boxes and classes. Let me introduce a comparisson. 

## With Yolov8 tracker (this repo):
![image](https://user-images.githubusercontent.com/17271049/215123793-ffafb985-6188-4b82-ad51-3c26caa6f4fa.png)

## With Yolov8 (ultralytics, no tracking):
![image](https://user-images.githubusercontent.com/17271049/215125665-4f252cd2-b00e-4956-90c1-205c409ce6ef.png)

## With Yolov5 and deepsort (a very old version of this repo):
![image](https://user-images.githubusercontent.com/17271049/215124425-9a24813e-d4a5-40a2-a108-b82d022ae545.png)

As you can see, bounding boxes are not being correctly updated. I tried to check the tracker but I still cannot understand where's the bug

Please, could you help me to check this?

Thanks in advance.

**Comment by hdnh2006** [comment]
Ok @mikel-brostrom I got more information that can help to improve the this repo. 

Unfortunately it took me the whole afternoon 😆😆😆😆 but I finally found something,

The problem is clearly with the default tracker (bytetracker).

### When I use `bytetrack` I got what I show you above:
![image](https://user-images.githubusercontent.com/17271049/215161407-e1819b2c-cec5-4fd0-9ccd-1e82b91ead7f.png)![image](https://user-images.githubusercontent.com/17271049/215161442-652ff0ca-257c-4177-a59a-1a76507922fe.png)

### With ocsort (equally faster than bytetrack but more cpu consumption):
![image](https://user-images.githubusercontent.com/17271049/215161197-bc595925-a9b6-4593-a126-feb09fa6bb5e.png)![image](https://user-images.githubusercontent.com/17271049/215161905-c5ba4351-0e5a-4c77-a7eb-2c8ce0b40e8f.png)

### With stronsort (the slowest one, but normal cpu consumption):
![image](https://user-images.githubusercontent.com/17271049/215162497-8c910ba9-9291-4d76-91e8-fc8f98ef4a06.png)

Mikel, is any difference between the update with `bytetracker` and `ocsort`? I'll try to help you checking both updates, but surely you can do it faster than anyone.

Thanks in advance.

**Comment by mikel-brostrom** [comment]
Could be that the handling of classes is a bit different. Have to look into that.
