### ISSUE TITLE
tracker evaluate other tracking targets

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [mikel-brostrom/yolov8_tracking#709]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hello, can the tracker evaluate other tracking targets? For example, the data set I built wanted to evaluate the tracking results, but when I used it, I said it could also be used for pedestrian evaluation. How should I modify it? Thank you

**Comment by mikel-brostrom** [comment]
As long as your custom dataset is in the same format as MOT, you can just:

python val.py --benchmark <name_of_your_custom_dataset>

**Comment by Zhengzhiyang0000** [comment]
Hello, I made MOT17 data using the visdrone dataset. When running val, an error will be reported. What is the problem? thank you
![Uploading image.png…]()

**Comment by mikel-brostrom** [comment]
What is the error? Provide the full output please

**Comment by Zhengzhiyang0000** [comment]
![image](https://user-images.githubusercontent.com/95676739/215313602-3db13704-9cfb-4874-b6c9-4a4a293ba278.png)

**Comment by Zhengzhiyang0000** [comment]
Trackeval evaluates the multi-target tracking results, which can be used for multi-category evaluation or only for pedestrian evaluation. If it needs to be modified, how should it be modified? Thank you

**Comment by mikel-brostrom** [comment]
Multi-category evaluation is not a problem at all. Tracking don't even take class into consideration when evaluating.

**Comment by Zhengzhiyang0000** [comment]
OK，thank you very much
