### ISSUE TITLE
Why don't you make a PR to the ultralytics repo?

### ISSUE THREAD

**Issue by aurelm95** [mikel-brostrom/yolov8_tracking#713]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I would like to know why this useful repo is not part of the ultralytics repo. Is it because this has nothing to do with the concept of their repo ? Or is it just because you want to own this code? or because they would not accept/maintain the code??

Thanks!

**Comment by mikel-brostrom** [comment]
The goal of this repo is to make SOTA tracking more available. I would like to create a pip package out of this at some point, independent of any specific object detector. Moreover, I would not have enough time to maintain both on my free time. We however collaborate actively to make computer vision more available to everybody. :rocket:

**Comment by aurelm95** [comment]
Great thanks for the explanation!
