### ISSUE TITLE
Why track id is not sequently?

### ISSUE THREAD

**Issue by madenburak** [mikel-brostrom/yolov8_tracking#715]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

While giving track_id to objects, it was not sequently. For example, 1,2,5,6,10 etc. Why this situation happens and how I solve it?

**Comment by mikel-brostrom** [comment]
Some tracks may never be initialized, loosing the ID assigned to them. Why is this an issue?

**Comment by madenburak** [comment]
If there is 3 object in frame, it must be (object 1-id=1;object 2-id=2; object 3-id=3) as sequently. Detector detects 3 object only but tracker give nonsequently id like (object 1-id=1;object 2-id=4; object 3-id=7). 

My question is that is problem on dedector? Or, should I another edit?

**Comment by mikel-brostrom** [comment]
You would need custom modifications to achieve this. Some kind on ID revival system

**Comment by madenburak** [comment]
Thanks @mikel-brostrom. I'll try it.
