### ISSUE TITLE
ImportError:  site-packages/lap/_lapjv.cpython-39-darwin.so  have 'x86_64', need 'arm64'

### ISSUE THREAD

**Issue by mingmingshen** [mikel-brostrom/yolov8_tracking#716]
Could you remove the mandatory dependency of lap in the project? ocsort and strongsort cannot be used on macbook m1 because of this dependency of bytetrack

<img width="945" alt="image" src="https://user-images.githubusercontent.com/43539521/216808315-9819a62d-4447-404e-bdca-32b9b944f8d7.png">

**Comment by mikel-brostrom** [comment]
It is part of the pipeline, so cannot do that. Sorry.

**Comment by mingmingshen** [comment]
> 

Ok, I can make my own comments to solve this problem thanks

**Comment by mingmingshen** [comment]
> It is part of the pipeline, so cannot do that. Sorry.

Ok I will comment code to solve this problem thanks
