### ISSUE TITLE
ReID after exiting the FOV of the camera

### ISSUE THREAD

**Issue by noahweber1-debug** [mikel-brostrom/yolov8_tracking#717]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is supervised tracking of objects possible?

This is the situation: Having 4 distinct objects, some of them leave the sight for extended period of time. When they rejoin the screen will they be assigned to their previous track ID?

**Comment by mikel-brostrom** [comment]
This completely depends on the scenario. And the quality of your custom models. It is impossible to tell
