### ISSUE TITLE
Multi-Camera Real time

### ISSUE THREAD

**Issue by vishyVishal** [mikel-brostrom/yolov8_tracking#718]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi. Please excuse me if this is a trivial question. I would like to understand better how it is able to achieve "real-time" detections + tracking for multi camera setup using multiple rtsp urls? thanks

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/293#issuecomment-1027641698
