### ISSUE TITLE
Error while using tracker on custom trained yolov8 segmentation model

### ISSUE THREAD

**Issue by andreazuna89** [mikel-brostrom/yolov8_tracking#720]
Hi,
Thanks for the great work. I was playing with your code and I was using a yolov8 segmentation model trained on a custom dataset. I get the following error:

YOLOv8x-seg summary: 295 layers, 71729323 parameters, 0 gradients, 343.7 GFLOPs
1/1: 0... Success (inf frames 640x480 at 30.00 FPS)

Traceback (most recent call last):
File "track.py", line 367, in
main(opt)
File "track.py", line 362, in main
run(**vars(opt))
File "/home/azunino/anaconda3/envs/tracking/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
File "track.py", line 220, in run
s += f"{n} {names[int(c)]}{'s' * (n > 1)}, " # add to string
KeyError: 12
Aborted (core dumped)

Can you help me here? That error comes only when I use a model pretrained on custom data.

Thanks
Andrea

**Comment by mikel-brostrom** [comment]
It seems to me that the class name count you saved with your models do not match the predicted number of classes...

**Comment by andreazuna89** [comment]
Can you explain a bit more? Where should I set the class name counts? The training on custom data worked well. Have you already tried the code with a model trained on custom data?

Thanks a lot
Andrea

**Comment by andreazuna89** [comment]
I cannot put the input stream=True as a parameter of the model.predict. Also, model.names gives: *** AttributeError: 'YOLO' object has no attribute 'names'.
I am not sure that it is a problem of yolov8 because the predict function is working with a yolo model trained on a custom dataset.

**Comment by mikel-brostrom** [comment]
Are you using the same `env` for both Ultralytics and this repo?

**Comment by andreazuna89** [comment]
I am following your guide here: 
git clone --recurse-submodules https://github.com/mikel-brostrom/yolov8_tracking.git  # clone recursively
cd yolov8_tracking
pip install -r requirements.txt  # install dependencies

**Comment by andreazuna89** [comment]
I guess the problem is in det[:, 5] in line 216 of track.py which contains ids bigger than the ids of the classes on which I was training the yolo con custom data. Do you know how is it possible? Is det[:, 5] containing the ids of the classes predicted, right? It is strange that a simple block of code which use a trained yolov8 model trained on custom data is working without errors:
```
from ultralytics.yolo.engine.model import YOLO
  
model = YOLO("PATH TO MODEL")

results = model.predict(source=0) 
```
Can you help me to understand?

Thanks

**Comment by andreazuna89** [comment]
I have discovered the problem :) When I was training the segmentation model on a custom dataset the name of the model was not containing the word 'seg'. So the flag in line 103
```
is_seg = '-seg' in str(yolo_weights)
```
was not activated as True and the produced detections were not formatted in a correct way, producing problems in the code. Now it is working,

Thanks
