### ISSUE TITLE
Saving a Video within the Dockerfile

### ISSUE THREAD

**Issue by buckeye17** [mikel-brostrom/yolov8_tracking#723]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

While running `track.py` within the Dockerfile provided by this repo, it silently fails to generate a video when the `--save-vid` flag is included in the command.  No error is produced in the terminal output and no video appears in the `save_path` directory.  As far as I can tell this is because the Dockerfile doesn't have ffmpeg installed.  Unfortunately the solution doesn't appear to be as simple as installing ffmpeg, because OpenCV won't know it exists without taking further steps.  I've been trying to modify the Dockerfile but haven't gotten it to work yet.  One problem I'm running into is that the `lap` package fails to install when I attempt to build OpenCV from source using this [Dockerfile](https://github.com/Borda/docker_python-opencv-ffmpeg/blob/master/cpu/Dockerfile) as a template to add within your Dockerfile.  Any help would be appreciated.

### Environment

I'm using the latest version of your repo with YOLOv8, running inside your Docker image (Ubuntu 20.04)

**Comment by mikel-brostrom** [comment]
Thanks for reporting this. I have not thoroughly tested the image. Could any of these solve it? This is what is installed in the ultralytics Yolov8 Docker image.

> RUN /bin/sh -c apt install --no-install-recommends -y libgl1-mesa-glx libglib2.0-0 libpython3-dev

**Comment by buckeye17** [comment]
I haven't been able to investigate solutions to this problem any further yet, but I have discovered that this issue also prevents `track.py` from ingesting video sources in the Docker container.  Currently I've written my own work arounds for these problems by using ffmpeg to turn videos into collections of images, as well as to turn collections of images into videos.  If I get the chance to resolve the Docker environment, I'll share my solution here.

**Comment by henriksod** [comment]
Hi, maybe you need to bind your host filesystem to the docker container?
[https://docs.docker.com/storage/bind-mounts/](https://docs.docker.com/storage/bind-mounts/)
