### ISSUE TITLE
question about segmentation masks

### ISSUE THREAD

**Issue by A1exy** [mikel-brostrom/yolov8_tracking#724]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

$ python track.py --yolo-weights yolov8n.pt     # bboxes only
                                yolov8-seg.pt  # bboxes + segmentation masks

Dear author, I have a  question about segmentation masks, does this  yolov8 model train detection and segmentation at the same time, I can't find it in the yolov8 official code. How do I do joint training?
Looking forward to your reply. 
Thanks.

**Comment by mikel-brostrom** [comment]
This is a question for: https://github.com/ultralytics/ultralytics
