### ISSUE TITLE
The StrongSORT you used does not have AFLink and GSI ?

### ISSUE THREAD

**Issue by Sumant-Gosi** [mikel-brostrom/yolov8_tracking#727]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Pardon me, if this is a sillly question.

I am unable to understand one thing. The StrongSORT official paper states the use of 2 plug and play modules i.e. AFLink and GSI.
But however, the StrongSORT you use, does not have these two modules. Instead, the strongSORT you are using makes use of Re-ID models. So, I am unable to understand if you are using a DeepSORT tracker or a StrongSORT.

It would be of great help, if I can get a clarification.

**Comment by mikel-brostrom** [comment]
Moreover, StrongSORT is not only these two plug and play modules

**Comment by Sumant-Gosi** [comment]
I understand, thank you very much.
