### ISSUE TITLE
save_crop function does not exist.

### ISSUE THREAD

**Issue by netrosec** [mikel-brostrom/yolov8_tracking#730]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

When the `--save-crop`  command argument is passed the code throws this error: 
  
```
  `File "track.py", line 267, in run
    save_one_box(np.array(bbox, dtype=np.int16), imc, file=save_dir / 'crops' / txt_file_name / names[c] / f'{id}' / f'{p.stem}.jpg', BGR=True)
NameError: name 'save_one_box' is not defined`
```
It appears the `save_one_box` function is not defined anywhere in the code.

**Comment by mikel-brostrom** [comment]
Thank you for reporting. This is now fixed in master
