### ISSUE TITLE
strongsort项目代码相关问题​ Strongsort project code related issues

### ISSUE THREAD

**Issue by eoozbq** [mikel-brostrom/yolov8_tracking#733]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello, I used your previous version, version link: https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/tree/botsort
In this version, the 147th line in the track.py file is bootrot_ list and 147-153 is the code related to BoTSORT, and this project is StrongSORT. Is this part of the code correct?

**Comment by mikel-brostrom** [comment]
BoTSORT is a different tracker we are working on
