### ISSUE TITLE
i want to use GPU to accelerate the tracker part

### ISSUE THREAD

**Issue by zfs1993** [mikel-brostrom/yolov8_tracking#734]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

i understand how to accelerate the yolo part with gpu, but the trakcer part consumes lots of cpu resources, so i want to use gpu to accelerate the tracker part, does anyone have any ideas about it ,thanks very much

**Comment by mikel-brostrom** [comment]
The trackers are built to work on CPU. They have are no cuda implementation. The only thing that runs on GPU are the ReID models.

**Comment by zfs1993** [comment]
> 



> The trackers are built to work on CPU. They have are no cuda implementation. The only thing that runs on GPU are the ReID models.

thanks very much ,can i find any trackers which consume less computation with cpu?when the objections is more than 20, cpu consumption rise rapidly. or can i find a tracker has cuda implementation
