### ISSUE TITLE
想請問yolo不同版本的track

### ISSUE THREAD

**Issue by stphtan94117** [mikel-brostrom/yolov8_tracking#736]
作者你好
我想請問目前現階段的版本-yolov8_tracking，是否支援其他版本yolo權重
例如使用yolov7 or yolov5的pt，是否能在yolov8_tracking專案執行?

另外想請教一下，因為yolov5版本，有太多子版本，據我了解 6.1、6.2、7.0權重架構都不相同
不知道作者的專案，是否有相容到多個yolov5分支，謝謝

**Comment by mikel-brostrom** [comment]
https://github.com/ultralytics/ultralytics/issues/601

**Comment by stphtan94117** [comment]
> 

可是這樣就沒意義了阿，我就已經有了權重，例如是6.1版本的pt，那還得用Ultralytics 訓練，
那就直接訓練yolov8就好，還用yolov5就沒意思了

另外，那如果是yolov7版本，目前這個專案是否可以支援!?
謝謝

**Comment by mikel-brostrom** [comment]
Sure, training a Yolov8 model would be your best option. Otherwise you can just one an older release.  :smiley:
