### ISSUE TITLE
cannot use evolve.py script 

### ISSUE THREAD

**Issue by jw787** [mikel-brostrom/yolov8_tracking#737]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

**This is the bug when i use ocsort to evolve the MOT17**

evolve: yolo_weights=runs/detect/train5/weights/best.pt, reid_weights=/data/home/jwu/yolov8_tracking/weights/osnet_x1_0_dukemtmcreid.pt, tracking_method=ocsort, tracking_config=trackers/ocsort/configs/ocsort.yaml, name=exp, project=runs/evolve, exist_ok=False, benchmark=MOT17, split=train, eval_existing=, conf_thres=0.45, imgsz=[1280], device=[''], n_trials=10, resume=False, processes_per_device=2, objectives=['HOTA', 'MOTA', 'IDF1']
[I 2023-02-15 14:30:33,944] A new study created in memory with name: no-name-2c374dc0-1c34-48e5-aa84-72010ec6b450
[FrozenTrial(number=0, state=TrialState.WAITING, values=None, datetime_start=None, datetime_complete=None, params={}, user_attrs={}, system_attrs={'fixed_params': {'asso_func': 'giou', 'delta_t': 1, 'det_thresh': 0, 'inertia': 0.3941737016672115, 'iou_thresh': 0.22136877277096445, 'max_age': 50, 'min_hits': 1, 'use_byte': False}}, intermediate_values={}, distributions={}, trial_id=0, value=None)]
Eval repo already downloaded
######################################################################## 100.0%Warning: Transient problem: FTP error Will retry in 1 seconds. 3 retries left.
Warning: Transient problem: FTP error Will retry in 2 seconds. 2 retries left.
Warning: Transient problem: FTP error Will retry in 4 seconds. 1 retries left.

curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.
MOT17.zip downloaded sucessfully
MOT17.zip is corrupted. Try deleting the file and run the script again

Could you please help me solve this issue. Thanks a lot.

**Comment by mikel-brostrom** [comment]
Delete the MOT17.zip and run again

**Comment by jw787** [comment]
> Delete the MOT17.zip and run again

I have deleted MOT17.zip，but it doesn't work

**Comment by mikel-brostrom** [comment]
It seems that the `MOT17.zip` is not downloaded at all. Try to input the associated link in the web-browers

**Comment by mikel-brostrom** [comment]
What do you get if you search for: https://motchallenge.net/data/MOT17.zip

**Comment by Rm1n90** [comment]
Hey @mikel-brostrom, Im getting the same error when trying to run evolve.py even I downloaded the MOT17.zip from the link above you provided. It always say MOT17.zip is corrupted. Try deleting the file and run the script again

**Comment by mikel-brostrom** [comment]
Can you open it manually?

**Comment by Rm1n90** [comment]
@mikel-brostrom, I think I fixed the issue with returning all the time XXX.zip is corrupted, Will send a PR soon (Testing now) :)

**Comment by Rm1n90** [comment]
Nothing related to the packages. The main issue was the improper use of os.path.exists() and os.path.isfile() when checking for the existence of the file.
