### ISSUE TITLE
multiple video/ip stream tracking IDS duplicated

### ISSUE THREAD

**Issue by faizelkDatapost** [mikel-brostrom/yolov8_tracking#741]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

if you are using multiple streams the IDS are duplicated example stream1 could have id 1,2,3 and stream2 also has id 1,2,3.
Should the ids not be unique/incremental across all streams?

example
`python3 track.py --source streams.txt --yolo-weights yolov8s.pt --tracking-method strongsort`

example of how streams.txt content looks (line by line)
`/home/yolov8_tracking/video1.mp4`
`/home/yolov8_tracking/video2.mp4`

### Minimal Reproducible Example

example
`python3 track.py --source streams.txt --yolo-weights yolov8s.pt --tracking-method strongsort`

example of how streams.txt content looks (line by line)
`/home/yolov8_tracking/video1.mp4`
`/home/yolov8_tracking/video2.mp4`

**Comment by mikel-brostrom** [comment]
This is the expected behavior, the trackers don't share information among each other
