### ISSUE TITLE
Yolo version problem

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/yolov8_tracking#742]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

How can I continue to use yolov5 in the latest repo?（You have changed to YOLO v8）

**Comment by mikel-brostrom** [comment]
You can train Yolov5 models with the ultralytics repo and use those. I don't think old Yolov5 models are compatible with the new repo.

**Comment by Stephen-Ning** [comment]
> 您可以使用 ultralytics 存储库训练 Yolov5 模型并使用它们。我不认为旧的 Yolov5 模型与新的 repo 兼容。

thank you！
