### ISSUE TITLE
increment_ages

### ISSUE THREAD

**Issue by vladimircape** [mikel-brostrom/yolov8_tracking#744]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Here 
```
https://github.com/mikel-brostrom/yolov8_tracking/blob/master/trackers/strongsort/sort/tracker.py
https://github.com/mikel-brostrom/yolov8_tracking/blob/master/trackers/strongsort/strong_sort.py

```
i see 
`def increment_ages(self):`
but i didn't find where it used, based on your report such function not used
Also i didn't find such code in official repo of such tracker

**Comment by mikel-brostrom** [comment]
You are right, this is not being used. I should spend some time cleaning up the repo :smile:
