### ISSUE TITLE
Tracker predicts the same ID more than once in a single timestep.

### ISSUE THREAD

**Issue by hmquang01** [mikel-brostrom/yolov8_tracking#751]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I am running a MOT model on the training set of MOT17 (the model works by taking the detections from det.txt to do the tracking). Is there a way to evaluate the model results? I tried using JonathonLuiten's TrackEval but got the error [Tracker predicts the same ID more than once in a single timestep]. Thank you for your help and sorry for disturbing your discussion. I hope you can help me to solve it. (*)

**Comment by mikel-brostrom** [comment]
I have experienced this myself a few times when running `val.py`. I have not figured out though what the problem is...

**Comment by yaoshanliang** [comment]
How can we fix this problem?

**Comment by yaoshanliang** [comment]
When using HybridSORT, it actually output the same trackID twice in one frame, and then caused the problem as the title. Is it the problem from HybridSORT?

```
48 1 1863 478 56 17 0 1 -1
48 2 1452 420 197 62 0 2 -1
48 1 1861 468 58 27 0 2 -1
```
