### ISSUE TITLE
Can you include classes in the MOT txt file?

### ISSUE THREAD

**Issue by Cristofhersj** [mikel-brostrom/yolov8_tracking#752]
### Search before asking

- [ ] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello everyone!
In the project that I'm working on I need to gather the ID, location and the class of the object.
Is there a way that I can save the classes of the object in the txt generated when using --save-txt.
I also tried with the tracking tool in the ultralytics  but I find the opposite problem. The classes are saved, but the ID's don't

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/661
