### ISSUE TITLE
matching problem

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/yolov8_tracking#753]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Strongsort does not have iou matching。Only appearance measurement and motion measurement are used as matching methods for matching costs.Is my understanding right?

**Comment by mikel-brostrom** [comment]
You are right. If you want IoU matching you can try out BoTSORT :smile:

**Comment by Stephen-Ning** [comment]
![1677229438118](https://user-images.githubusercontent.com/108001646/221137710-5098830d-9f37-4c09-a178-4cfd82b58a30.jpg)
![1677229535271](https://user-images.githubusercontent.com/108001646/221137727-a9d384b5-df3f-45d5-9e6d-9266e878f719.jpg)

This is in tracker.py_ Match function
1.matching_ The cost of the cascade is the weighted sum of appearance and motion measures
2.min_ cost_ Matching is iou_ cost
Why do you say that only the weighted sum of appearance and motion measurements is used? I am very confused and look forward to your answer!

**Comment by Stephen-Ning** [comment]
![1677229880378](https://user-images.githubusercontent.com/108001646/221139020-c3f0815b-2879-46e0-a365-b8b3e047a63b.jpg)

Strongsort.py called the update function
As shown in the figure, update uses_ match

**Comment by Stephen-Ning** [comment]
![1677229438118](https://user-images.githubusercontent.com/108001646/221144211-074a121a-9e80-4bc0-b7cf-2912de46196c.jpg)
![1677229535271](https://user-images.githubusercontent.com/108001646/221144255-c90dbd07-1387-4e1b-acfe-a0cd855a10c3.jpg)

The first picture: matching_ Cascade You change it to linear distribution, and cost is the weighted sum of motion and appearance.
Second picture: min_ cost_ Matching is iou matching。

I'm confused! I looked at the code of 4.0 deepsort and found no difference here. Please help me.

**Comment by Stephen-Ning** [comment]
> [mikel-brostrom](/mikel-brostrom)

@mikel-brostrom

**Comment by mikel-brostrom** [comment]
Matching called:

https://github.com/mikel-brostrom/yolov8_tracking/blob/37b44e3963b5a0d39ec1b2ad312338fc7f808157/trackers/strongsort/sort/tracker.py#L91

Cost used:

https://github.com/mikel-brostrom/yolov8_tracking/blob/37b44e3963b5a0d39ec1b2ad312338fc7f808157/trackers/strongsort/sort/tracker.py#L156

It takes in the cosine distance cost matrix. This cost matrix is then gated by the distributions obtained by the KFs

**Comment by Stephen-Ning** [comment]
> Matching called:
> 
> https://github.com/mikel-brostrom/yolov8_tracking/blob/37b44e3963b5a0d39ec1b2ad312338fc7f808157/trackers/strongsort/sort/tracker.py#L91
> 
> Cost used:
> 
> https://github.com/mikel-brostrom/yolov8_tracking/blob/37b44e3963b5a0d39ec1b2ad312338fc7f808157/trackers/strongsort/sort/tracker.py#L156
> 
> It takes in the cosine distance cost matrix. This cost matrix is then gated by the distributions obtained by the KFs

_ The match function is divided into two matches, as shown in the two pictures above

**Comment by Stephen-Ning** [comment]
This is  definition of the _match function



   matches_a, unmatched_tracks_a, unmatched_detections = \
            linear_assignment.matching_cascade(
                gated_metric, self.metric.matching_threshold, self.max_age,
                self.tracks, detections, confirmed_tracks)

        iou_track_candidates = unconfirmed_tracks + [
            k for k in unmatched_tracks_a if
            self.tracks[k].time_since_update == 1]
        unmatched_tracks_a = [
            k for k in unmatched_tracks_a if
            self.tracks[k].time_since_update != 1]
        matches_b, unmatched_tracks_b, unmatched_detections = \
            linear_assignment.min_cost_matching(
                iou_matching.iou_cost, self.max_iou_distance, self.tracks,
                detections, iou_track_candidates, unmatched_detections)

**Comment by mikel-brostrom** [comment]
Aha, yes I see what you mean. IoU is used for everything but the confirmed ones. The confirmed ones uses feature and motion appearance.

**Comment by Stephen-Ning** [comment]
> 啊哈，是的，我明白你的意思。IoU 用于除已确认的以外的所有内容。已确认的使用功能和运动外观。所以StrongSORT的主要关联方式是motion + feature appearance

Wow! Thank you for your reply! I would be very grateful!

**Comment by mikel-brostrom** [comment]
Usually the association method for each type of track is different (unconfirmed tracks, confirmed tracks, ...). In [BOTSORT](https://github.com/NirAharon/BoT-SORT/blob/251985436d6712aaf682aaaf5f71edb4987224bd/tracker/bot_sort.py#L309-L314), when using ReID the cost matrix is based on IoU distance and appearance. There are many options here... :smile:

**Comment by Stephen-Ning** [comment]
> , dets , track_indices , detection_indices , self.mc_lambda ) _ _

Thank you for your ideas. I will try to match and try the effect! (Your project has taught me a lot of knowledge, thank you!)

**Comment by mikel-brostrom** [comment]
> Your project has taught me a lot of knowledge, thank you!

Glad to help :smile:
