### ISSUE TITLE
strongsort without reid model 

### ISSUE THREAD

**Issue by AprilWinds** [mikel-brostrom/yolov8_tracking#754]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

May I ask how the Strong SORT algorithm works without using the reid model?

**Comment by mikel-brostrom** [comment]
Set

https://github.com/mikel-brostrom/yolov8_tracking/blob/40b2a02c40d836833969b2e2cc016ce48ad7206f/trackers/strongsort/configs/strongsort.yaml#L8

to 0.

This will nullify the appearance descriptor contribution and only use motion. The ReID model will however still be executed.
