### ISSUE TITLE
yolov5 tracker 

### ISSUE THREAD

**Issue by Younis-Matouq** [mikel-brostrom/yolov8_tracking#755]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

hello, I was wondering if you still had a yolov5 tracker?

**Comment by mikel-brostrom** [comment]
Clone the v8 release:

https://github.com/mikel-brostrom/yolov8_tracking/issues/758#issuecomment-1454810089
