### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by DevinduDh** [mikel-brostrom/yolov8_tracking#756]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I just cloned the repo from github and installed the requirements and I'm getting this error.

 from ultralytics.yolo.utils.checks import check_yolo as checks
ImportError: cannot import name 'check_yolo' from 'ultralytics.yolo.utils.checks'

**Comment by LuccaBuffara** [comment]
I had the same error because I forgot to clone the submodules.

Running the following worked for me:
`git clone --recurse-submodules https://github.com/mikel-brostrom/yolov8_tracking.git`
