### ISSUE TITLE
Can you provide yolov5_strongsort_osnet?

### ISSUE THREAD

**Issue by fireppGo** [mikel-brostrom/yolov8_tracking#758]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

There are a lot of problems in the new yolov8_tracking. For example, I can't get correct result by strongsort.

**Comment by mikel-brostrom** [comment]
Just grab the v8 release :smile: 

https://github.com/mikel-brostrom/yolov8_tracking/tree/78968a0189823515c8bddfba27c8b00949e55014
