### ISSUE TITLE
pose-estimation

### ISSUE THREAD

**Issue by xcf11111** [mikel-brostrom/yolov8_tracking#759]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

可以再加一个姿态估计嘛

**Comment by mikel-brostrom** [comment]
Yolov8 doesn't have pose-estimation, this means that you won't see pose estimation unless you substitute yolov8 by a pose estimation model.
