### ISSUE TITLE
object tracking results not perfect, assiging wrong names while doing tracking

### ISSUE THREAD

**Issue by akashAD98** [mikel-brostrom/yolov8_tracking#760]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I'm trying to apply reid weight to my custom-trained model, i want to do tracking of objects,
its detecting objects correctly, but somethimes its giving wrong labels , may i know whats the reason behind it?,sometimes its detecting correct results, sometimes its giving wrong names

below you can see, for t-shirt its giving a belt,as a prediction

<img width="640" alt="image" src="https://user-images.githubusercontent.com/62583018/222971628-aa83c862-295b-4f6d-848f-f67e00f4299e.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/62583018/222971801-5f5f6067-32d1-4025-b848-b9b0d8d7ba22.png">

for shirt its showing pant, & pant its showing shirt,

i just want to know what are the posiblities of giving this results? is my model wrong, or i need to play with parametrs,?

**Comment by mikel-brostrom** [comment]
This is a known bug in bytetrack. Use strongsort, botsort or ocsort
in the case you don't need that tracker specifically for some reason :smile:

**Comment by akashAD98** [comment]
@mikel-brostrom actually im using deep sort, like may I know what should be issue then? im asking this question because you have experimented different object trackers,

**Comment by imbiganna** [comment]
Hi, I encountered the same problem as you. Have you solved it?
