### ISSUE TITLE
How is ground truth derived?

### ISSUE THREAD

**Issue by adelinawong** [mikel-brostrom/yolov8_tracking#761]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Would like to know how does ground truth come about for the MOT challenge benchmark. Is the ground truth manually labelled or is it run against a certain tracker and the result becomes the ground truth? Thank you and hope to hear from you soon!

**Comment by mikel-brostrom** [comment]
Citing the official benchmark page:

> All sequences have been annotated with high accuracy, strictly following a well-defined protocol.
