### ISSUE TITLE
How can I achieve the goal of jumping frames for detecting

### ISSUE THREAD

**Issue by a773808735** [mikel-brostrom/yolov8_tracking#763]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Dear Mikel, I appreciate a lot for your excellent work. I wonder how I can jump every 5 frames to detect, and use deepsort to track every frame, cause I wanna enhance the speed of my detecting model.

**Comment by mikel-brostrom** [comment]
`python track.py --vid-stride 5`

**Comment by a773808735** [comment]
> 

Thanks for your kind help. But I am using an old version of code. I can cite this code with
@misc{yolov5deepsort2020,
    title={Real-time multi-object tracker using YOLOv5 and deep sort},
    author={Mikel Broström},
    howpublished = {\url{https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch}},
    year={2020}
}
How can I jump every 5 frames to detect, and use deepsort to track every frame, cause I wanna enhance the speed of my detecting model.

**Comment by mikel-brostrom** [comment]
This features was not available there. Sorry. There is certainly a way of achieving this with that version but not my prio

**Comment by a773808735** [comment]
Hi, Mikel. How can I stop using ReID model in version 8. Setting mc_lambda to 0 seems does't work.
