### ISSUE TITLE
Is yolov8 is capable for Lane detection?

### ISSUE THREAD

**Issue by Kd-Here** [mikel-brostrom/yolov8_tracking#764]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I learn how to find lane detection with yolo-5 
But find difficult to do same with yolo-8

**Comment by mikel-brostrom** [comment]
It is capable of whatever you train it to detect/segment limited by the quality and volume of your data
