### ISSUE TITLE
error：

### ISSUE THREAD

**Issue by Ai-nobody** [mikel-brostrom/yolov8_tracking#766]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

: cannot connect to X server，

it apply in  linux server

### Environment

Ultralytics YOLOv8.0.20 🚀 Python-3.6.9 torch-1.9.0+cu111 CUDA:0 (NVIDIA GeForce RTX 3090, 24268MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

### Minimal Reproducible Example

YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
: cannot connect to X server

**Comment by mikel-brostrom** [comment]
have you ssh'd into it with `-X` flag?

`ssh -X ...`

**Comment by Ai-nobody** [comment]
yes，ssh into my server，does it need  visual interface？
