### ISSUE TITLE
val.py

### ISSUE THREAD

**Issue by zhinengxiaolongxia** [mikel-brostrom/yolov8_tracking#768]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

![截图 2023-03-08 13-23-48](https://user-images.githubusercontent.com/105970214/223632439-2cb2a91f-8f00-4bc0-999e-81e1614bc25a.png)

您好，首先感谢您的开源代码！我评估的时候发现这个问题，您看是什么原因

**Comment by mikel-brostrom** [comment]
`git pull`

This value is included in the config for `StrongSORT`:

https://github.com/mikel-brostrom/yolov8_tracking/blob/1013f310bcd1c7e768fde091df12cf4a425d3220/trackers/strongsort/configs/strongsort.yaml#L11

**Comment by zhinengxiaolongxia** [comment]
谢谢，大神，这个问题解决了，评估时好像下载mot17.zip速度太慢如何解决

**Comment by zhinengxiaolongxia** [comment]
谢谢大神，这个问题解决了，评估时下载mot17.zip速度太慢如何快速解决，能加您好友吗，想请教您问题

**Comment by zhinengxiaolongxia** [comment]
谢谢大神，这个问题解决了，评价时下载mot17.zip速度太慢如何快速解决，能加您好友吗，想请教您问题

**Comment by zhinengxiaolongxia** [comment]
我微信，WX860843424
