### ISSUE TITLE
Getting error ''No such file or directory: '/content/yolov8_tracking/weights'''

### ISSUE THREAD

**Issue by PakiGuy** [mikel-brostrom/yolov8_tracking#771]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hi,
my code was working completely fine last week but now I am trying to run the deep sort code and I am getting errors. and I have tried to solve it but couldn't. Could you please have a look and help? I shall be thankful to you.

![image](https://user-images.githubusercontent.com/83809550/223754046-0ad2f6a9-9e3f-408b-b7c2-823c511bfb64.png)

**Comment by brarrow** [comment]
Manually create 'weights' directory in core directory 'yolov8_tracking'.

@mikel-brostrom  In code need to add mkdir('weights') before downloading weights.
