### ISSUE TITLE
mot16数据集测试

### ISSUE THREAD

**Issue by zhinengxiaolongxia** [mikel-brostrom/yolov8_tracking#772]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

![截图 2023-03-09 11-00-06](https://user-images.githubusercontent.com/105970214/223905442-1768e172-53fd-48aa-9602-a1db79ee71cb.png)
mot16和17在strongsort和botsort评估测试时出现上面错误卡住，在bytetrack和ocsort上测试正常，请教一下哪里出问题了，麻烦了

**Comment by mikel-brostrom** [comment]
This seems to be a problem for Chinese users only. Try to download it manually.

**Comment by zhinengxiaolongxia** [comment]
下载什么，没懂？mot数据集是自己下载的

**Comment by zhinengxiaolongxia** [comment]
下载什么？没懂。mot数据集是自己下载的

**Comment by mikel-brostrom** [comment]
You connection times out. If you have downloaded all the necessary files you can simply comment out the download blocks of code
