### ISSUE TITLE
Error: "trackeval.utils.TrackEvalException: ini file does not exist: out/seqinfo.ini"

### ISSUE THREAD

**Issue by nekvi** [mikel-brostrom/yolov8_tracking#775]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I am trying several days run evolve.py using my own custom dataset, i have followed the data structure you provide at "How to evaluate on a custom dataset" but i don't find a solution.

My data structure is exactly like this:
Path: /val_utils/data/gt/mot_challenge/
```
MOTCUSTOM-test
├── out
│   ├── gt
│   │   └── gt.txt
│   └── seqinfo.ini
```

seqinfo.ini is like this "

```
[Sequence]
name=out
seqLength=546
```
I have also try a lot of varieties of seqinfo so i don't think this is a problem (it just cannot find it)
Out of MOTCUSTOM-test i have seqmaps folder with MOTCUSTOM-test.txt :
 ```
name
out
```
Finally i have val_utils/data/MOTCUSTOM/test/out/out  where at this folder i have put all my .jpgs with %6d order 
After running the command:
```
python evolve.py --yolo-weights /.../weights/best.pt --tracking-method strongsort --benchmark MOTCUSTOM --split test --objective HOTA --n-trials 100 --reid-weights .../resnet50/model/resnet50_model.pth.tar-100
```
the tracking pipeline is running correct but when it gets to trackeval/datasets/mot_challenge_2d_box.py i get the error:

```
raise TrackEvalException('ini file does not exist: ' + seq + '/' + os.path.basename(ini_file))
trackeval.utils.TrackEvalException: ini file does not exist: out/seqinfo.ini
```

i have try to get in touch with you through email but i didn't get an answer

**Comment by mikel-brostrom** [comment]
Thanks @nekvi for poing out that following the custom eval instructions is not working for you

**Comment by mikel-brostrom** [comment]
I will have a look into this today

**Comment by mikel-brostrom** [comment]
The instructions are not reflecting the latest changes in `val.py`. Updating

**Comment by mikel-brostrom** [comment]
Updated!

**Comment by mikel-brostrom** [comment]
> Tracker MOTCUSTOM was unable to be evaluated.
> Attempting to evaluate using invalid gt classes. This warning only triggers if preprocessing is performed, e.g. not for MOT15 or where prepropressing is explicitly disabled. Please either check your gt data, or disable preprocessing. The following invalid classes were found in timestep 2: -1

How can you have a class labeled -1 in your `gt.txt`?

**Comment by nekvi** [comment]
I have -1 only in the last 3 columns as MOTChallenge-format.txt suggest if you have 2D video. I don't know how it says -1 referred to a class. Even if i put -1 in the last four columns i also get the same error only with this format i get correct results :

```
11,1,1476.81,369.45,45.76999999999998,44.870000000000005,1,1,1,1
```

**Comment by mikel-brostrom** [comment]
Ahaa, I see. Yes, -1 is only for the ignore values in the generated detections. But this does not apply to the GT. If this was unclear I should add it to the WIKI. What do you think @nekvi?

**Comment by nekvi** [comment]
Wiki was very easy to follow, thanks you mikel...i am working on this so if i have any feedback i will let you know!
