### ISSUE TITLE
可以提供Yolov5_DeepSort_Pytorch的專案或網址嗎

### ISSUE THREAD

**Issue by ChingIvy** [mikel-brostrom/yolov8_tracking#777]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

不好意思，我想請問一下，能否提供Yolov5_DeepSort_Pytorch的專案或網址，我看您好像升級成yolov8了，非常感謝。
我是按照這個網頁的教學，我想跟著做網頁最後面的車流量的辨識，但似乎連結的網址換了。https://officeguide.cc/pytorch-yolo-v5-object-car-detection-calculate-traffic-flow-tutorial-examples/

**Comment by a773808735** [comment]
I have already achieved replacing yoloV8 model to yoloV5 v7.0. I am willing to help you, you can contact me via email or wechat. Besides, you can simply use mikel's code. Just in this repository, code--release--v5.0

**Comment by lpc-eol** [comment]
have the same request

**Comment by lpc-eol** [comment]
> I have already achieved replacing yoloV8 model to yoloV5 v7.0. I am willing to help you, you can contact me via email or wechat. Besides, you can simply use mikel's code. Just in this repository, code--release--v5.0

It helps. Thank you!

**Comment by stphtan94117** [comment]
> I have already achieved replacing yoloV8 model to yoloV5 v7.0. I am willing to help you, you can contact me via email or wechat. Besides, you can simply use mikel's code. Just in this repository, code--release--v5.0

你好 我有需要 yolov5-7.0版本 不知道是否有其他追蹤功能（bytetrack strongsort botsort...）
email
geoxpertdataxquad@gamil.com
謝謝

**Comment by geoxpert0001** [comment]
> I have already achieved replacing yoloV8 model to yoloV5 v7.0. I am willing to help you, you can contact me via email or wechat. Besides, you can simply use mikel's code. Just in this repository, code--release--v5.0

你好 我有需要 yolov5-7.0版本 不知道是否有其他追蹤功能（bytetrack strongsort botsort...）
email
geoxpertdataxquad@gamil.com
謝謝
