### ISSUE TITLE
Extracting Object velocity and position from Kalman filter

### ISSUE THREAD

**Issue by akshayj04** [mikel-brostrom/yolov8_tracking#779]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

How do I get object velocity between 2 consecutive frames and bounding box midpoint coordinates for each frame in both offline and real-time videos using Kalman filter? Also, will i get the velocities in pixel/sec or pixel/frame? Any help would be greatly appreciated. Thanks in advance!

**Comment by mikel-brostrom** [comment]
But the basic idea is to know how many pixels the object moved from one frame to another. Then you have to translate the pixels to distance. Finally you know how long time it too to calculate this from frame to frame. Having all the information you need. You can apply a rolling average on top to get more stable velocities

**Comment by akshayj04** [comment]
> The basic idea is to know how many pixels the object moved from one frame to another. Then you have to translate the pixels to distance. Finally you know how long time it too to calculate this from frame to frame. Now you have all the information you need. You can apply a rolling average on top to get more stable velocities

Yes, I was trying the same method. So, would just putting a timestamp in milliseconds for each frame and using that to calculate time between 2 frames be accurate for real time feed? I assumed it will also consider the processing time for the frames so it may not be accurate. Or should i just assume time between each frames to be 1/(FPS of camera)?

**Comment by mikel-brostrom** [comment]
Ideally, `1/the complete tracking looptime`
