### ISSUE TITLE
 No module named 'yolov8.ultralytics'

### ISSUE THREAD

**Issue by ChenShupan** [mikel-brostrom/yolov8_tracking#780]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello!
I appear when running the track.py file.

D:\ProgramData\Anaconda3\envs\yolov8_tracking-master\python.exe E:\PYYYYYY\yolov8_tracking-master\track.py 
Traceback (most recent call last):
  File "E:\PYYYYYY\yolov8_tracking-master\track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
ModuleNotFoundError: No module named 'yolov8.ultralytics'

Could you tell me how to solve this problem?

**Comment by Han21-yes** [comment]
I met the same problem and solved it. 
Try to download the latest version of ultralytics.（e.g.  pip install ultralytics==8.0.45）

**Comment by mikel-brostrom** [comment]
Please, follow the[installation instructions](https://github.com/mikel-brostrom/yolov8_tracking#installation). A mismatch in the ultralytics pip install can break the repo

**Comment by ChenShupan** [comment]
> 我遇到了同样的问题并解决了。 试试下载最新版本的ultralytics。（例如pip install ultralytics==8.0.45）

Hello, I tried your method and still failed.

**Comment by KyungRyeolBaek** [comment]
Hello, Are you solve this problem? @ChenShupan 
I try to uninstall ultralytics and install ultralytics==8.0.45, but I have same problem.
How to solve this problem?

**Comment by KyungRyeolBaek** [comment]
I solved this problem. @ChenShupan 
I should have done '--recurse-submodules' when doing the git clone, but I forgot.

git clone --recurse-submodules https://github.com/mikel-brostrom/yolov8_tracking.git
I solved it by doing a git clone again with the above phrase.

**Comment by ChenShupan** [comment]
> 
thank you

**Comment by Kay545** [comment]
I use "pip install ultralytics==8.0.45" slove this issue
