### ISSUE TITLE
using custom reid model

### ISSUE THREAD

**Issue by gbo999** [mikel-brostrom/yolov8_tracking#781]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

i have this resnet50.pth.tar-60  that been created with torchreid. i am trying to use it with your libary, but it requires .pt files. so i changed the file name to .pt. but then i got this:
is there a way to load custom weights that are not automatic download?
Available .pt ReID models for automatic download
['resnet50_market1501.pt', 'resnet50_dukemtmcreid.pt', 'resnet50_msmt17.pt', 'resnet50_fc512_market1501.pt', 'resnet50_fc512_dukemtmcreid.pt', 'resnet50_fc512_msmt17.pt', 'mlfn_market1501.pt', 'mlfn_dukemtmcreid.pt', 'mlfn_msmt17.pt', 'hacnn_market1501.pt', 'hacnn_dukemtmcreid.pt', 'hacnn_msmt17.pt', 'mobilenetv2_x1_0_market1501.pt', 'mobilenetv2_x1_0_dukemtmcreid.pt', 'mobilenetv2_x1_0_msmt17.pt', 'mobilenetv2_x1_4_market1501.pt', 'mobilenetv2_x1_4_dukemtmcreid.pt', 'mobilenetv2_x1_4_msmt17.pt', 'osnet_x1_0_market1501.pt', 'osnet_x1_0_dukemtmcreid.pt', 'osnet_x1_0_msmt17.pt', 'osnet_x0_75_market1501.pt', 'osnet_x0_75_dukemtmcreid.pt', 'osnet_x0_75_msmt17.pt', 'osnet_x0_5_market1501.pt', 'osnet_x0_5_dukemtmcreid.pt', 'osnet_x0_5_msmt17.pt', 'osnet_x0_25_market1501.pt', 'osnet_x0_25_dukemtmcreid.pt', 'osnet_x0_25_msmt17.pt', 'osnet_ibn_x1_0_msmt17.pt', 'osnet_ain_x1_0_msmt17.pt']

**Comment by mikel-brostrom** [comment]
The model type is not embedded into the models, hence they architectures have to be inferred from the model's name. Try to rename you weights to: `resnet50_market1501.pt`

**Comment by gbo999** [comment]
it doesn't have errors. but how do i know if it is not downloaded and used my own weights?

**Comment by mikel-brostrom** [comment]
the weights are just downloaded if nthey don't exist:

https://github.com/mikel-brostrom/yolov8_tracking/blob/03fc3dfcfe33f8a363b5b9a4b776e38060f8a367/trackers/strongsort/reid_multibackend.py#L59-L60

**Comment by mikel-brostrom** [comment]
the weights are just downloaded if they don't exist:

https://github.com/mikel-brostrom/yolov8_tracking/blob/03fc3dfcfe33f8a363b5b9a4b776e38060f8a367/trackers/strongsort/reid_multibackend.py#L59-L60
