### ISSUE TITLE
How to give different colors to the trajectories generated by different objects

### ISSUE THREAD

**Issue by ChenShupan** [mikel-brostrom/yolov8_tracking#783]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

How to give different colors to the trajectories generated by different objects

**Comment by mikel-brostrom** [comment]
Pass the color you want to the trajectory plotter:

https://github.com/mikel-brostrom/yolov8_tracking/blob/03fc3dfcfe33f8a363b5b9a4b776e38060f8a367/trackers/strongsort/strong_sort.py#L144

in (R, G, B) format
