### ISSUE TITLE
StrongSORT++

### ISSUE THREAD

**Issue by as51340** [mikel-brostrom/yolov8_tracking#784]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hi, are there any plans to integrate AFLink and GSI to the existing StrongSORT implementation?

**Comment by mikel-brostrom** [comment]
I focus on real-time stuff only. AFLink and GSI are postprocessing steps which can only be applied off the loop. I have no plan implementing this. But feel free to leave a PR!

**Comment by Edward-YS** [comment]
> I focus on real-time stuff only. AFLink and GSI are postprocessing steps which can only be applied off the loop. I have no plan implementing this. But feel free to leave a PR!

Hello
So in your words, GSI can't be used in real-time tracking to solve the problem of trajectory fragmentation?Does it make sense?
