### ISSUE TITLE
Is it possible to save gallery between restarts ?

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/yolov8_tracking#788]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Im not sure if gallery is the correct term to use, but would it be possible to save the tracking meta data between restarts. 

Why I would like to do this is because sometimes I don't have control of the system switching off (just a few seconds) and would like on restart that the model does not allocate new IDs to currently tracked objects as this will skew the count of objects.

Would appreciate any direction regarding this. I have a feeling the answer is within the _match method in tracker.py but I have not spent time attempting to understand how the KF is implemented and functions.

much appreciated

**Comment by mikel-brostrom** [comment]
> and would like on restart that the model does not allocate new IDs to currently tracked objects as this will skew the count of objects

For this to work you would need to save all the tracks with all the information they contain before shutdown. And load them again before the system is up and running. But then the previously saved motion and appearance information may have changed drastically lead to ID switches anyways.
