### ISSUE TITLE
detections = [STrack(xyxy, s, c) for (xyxy, s, c) in zip(dets, scores_keep, clss_keep)]

### ISSUE THREAD

**Issue by OOHAN-zxy** [mikel-brostrom/yolov8_tracking#790]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

I don't know if there is something wrong with my understanding. I think it is a mistake and I need your help.

In the byte_tracker.py
line 201:
dets_second = xywh[inds_second]
dets = xywh[remain_inds]

but
line 201:
detections = [STrack(xyxy, s, c) for (xyxy, s, c) in zip(dets, scores_keep, clss_keep)]

Why not the following:

dets_second = xyxys[inds_second]
dets = xyxys[remain_inds]

detections = [STrack(STrack.tlbr_to_tlwh(tlbr), s, c) for (tlbr, s, c) in zip(dets, scores_keep, clss_keep)]

**Comment by yihangZhu1729** [comment]
Hi, I also found some similar bugs in tracker/bot_sort.py:
(1)
L294: `dets = xywh[remain_inds]`
with L310 to L311:
```
detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
                              (xyxy, s, c, f) in zip(dets, scores_keep, classes_keep, features_keep)]
```
and (2)
L293: `dets_second = xywh[inds_second]`
with L385~388:
```
if len(dets_second) > 0:
    '''Detections'''  
    detections_second = [STrack(STrack.tlbr_to_tlwh(tlbr), s, c) for
        (tlbr, s, c) in zip(dets_second, scores_second, clss_second)]
```

**Comment by OOHAN-zxy** [comment]
> 嗨，我还在 tracker/bot_sort.py 中发现了一些类似的错误： (1) L294：`dets = xywh[remain_inds]` 从 L310 到 L311：
> 
> ```
> detections = [STrack(xyxy, s, c, f.cpu().numpy()) for
>                               (xyxy, s, c, f) in zip(dets, scores_keep, classes_keep, features_keep)]
> ```
> 
> (2) L293:`dets_second = xywh[inds_second]` 与 L385~388:
> 
> ```
> if len(dets_second) > 0:
>     '''Detections'''  
>     detections_second = [STrack(STrack.tlbr_to_tlwh(tlbr), s, c) for
>         (tlbr, s, c) in zip(dets_second, scores_second, clss_second)]
> ```

I don't understand why this is still accurate in the end.

In the byte_tracker.py
line 305
xyxy = xywh2xyxy(tlwh)

I'm not sure if this is relevant, and hope you can help me, thank you!

**Comment by yihangZhu1729** [comment]
Hi, @OOHAN-zxy. Currently, the exp run by simply uing `python val.py --benchmark MOT17 --tracking-method botsort` returned unsatisfying results (like -10% in MOTA and HOTA). I may do some experiments today with "corrected" codes, hopely I can figure out what's going wrong and inform you later.

**Comment by OOHAN-zxy** [comment]
> Hi, @OOHAN-zxy. Currently, the exp run by simply uing `python val.py --benchmark MOT17 --tracking-method botsort` returned unsatisfying results (like -10% in MOTA and HOTA). I may do some experiments today with "corrected" codes, hopely I can figure out what's going wrong and inform you later.

Thank you for your help and look forward to your reply.

**Comment by yihangZhu1729** [comment]
Hi @OOHAN-zxy. It seems that some of the codes confuse the **xywh** format with **tlwh** format, and after I correct these error, an increase of 0.5～1% increase is observed in the MOTA and HOTA (under my settings: mot17, yolov8m, resnet50, botsort). The performance enhancement is not significant and may or may not be related to the code change. 
Hope this can help you, and I also want to know the results if you run the experiment, so that I can know if this is a coincidence.

**Comment by OOHAN-zxy** [comment]
> Hi @OOHAN-zxy. It seems that some of the codes confuse the **xywh** format with **tlwh** format, and after I correct these error, an increase of 0.5～1% increase is observed in the MOTA and HOTA (under my settings: mot17, yolov8m, resnet50, botsort). The performance enhancement is not significant and may or may not be related to the code change. Hope this can help you, and I also want to know the results if you run the experiment, so that I can know if this is a coincidence.

Thank you for your reply. Could you please tell me the specific location of the code you correct in the file?

**Comment by OOHAN-zxy** [comment]
> > > Hi @OOHAN-zxy. It seems that some of the codes confuse the **xywh** format with **tlwh** format, and after I correct these error, an increase of 0.5～1% increase is observed in the MOTA and HOTA (under my settings: mot17, yolov8m, resnet50, botsort). The performance enhancement is not significant and may or may not be related to the code change. Hope this can help you, and I also want to know the results if you run the experiment, so that I can know if this is a coincidence.
> > 
> > 
> > Thank you for your reply. Could you please tell me the specific location of the code you correct in the file?
> 
> Since I only use Bot-SORT as the tracking method, I only change codes in the tracker/bot_sort.py and yolov8/ultralytics/yolo/utils/ops.py. I'll list all my changes for you reference: (1) add a static method in STrack class in bot_sort.py, to change xywh to tlwh, mostly same as other convertion functions in that class. (2) call the above function in L310 ~ L311 and L387 ~ L388 in bot_sort.py to replace the origin "xyxy" and "tlbr" respectively (in fact in the xywh-format) (3) add an function in yolov8/ultralytics/yolo/utils/ops.py, to convert tlwh to xyxy. It is called in L466 in bot_sort.py to replace the origin "xywh2xyxy" function. I'd be happy if it works for you. 😊


Thank you very much for your help!

 Because I use Bytetrack as the tracking method, I correct the code as I understand it in the byte_tracker.py and run a demo file, but it doesn't work very well. I'll list all my changes:
(1)In L189~L190
dets_second = xyxys[inds_second]
dets = xyxys[remain_inds] 
(2)In L201 and L238
detections = [STrack(STrack.tlbr_to_tlwh(tlbr), s, c) for (tlbr, s, c) in zip(dets, scores_keep, clss_keep)]
detections_second = [STrack(STrack.tlbr_to_tlwh(tlbr), s, c) for (tlbr, s, c) in zip(dets_second, scores_second, clss_second)]
(3)In L305
xyxy = tlwh2tlbr(tlwh)
(4)The conversion functions I defined is as follows:
    def tlbr_to_tlwh(tlbr):
        ret = np.asarray(tlbr).copy()
        ret[2:] -= ret[:2]
        return ret

def tlwh2tlbr(x):
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[2:] += y[:2]
    return y

I don't know what the problem is, and hope I can get your help, thank you!
