### ISSUE TITLE
Id duration statistics.

### ISSUE THREAD

**Issue by fenguan** [mikel-brostrom/yolov8_tracking#791]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

HI, Recently I ran through your model on colab and generated a long trajectory，I have two questions for you about this trajectory.
1.How to accumulate the time when an id appears and generate a prompt after reaching the time threshold.① Can the trajectory change from black to red when the threshold is reached? ②How should I operate on the data of this id, such as storing the crop in another folder.
2. I saw how to modify the length of the trajectory from the issue, but I want to realize how the trajectory exists with people, and the trajectory disappears only when the person disappears.
Maybe my question is too detailed, thank you for your reply.

**Comment by mikel-brostrom** [comment]
You can get the time when the track is created and again when the track is killed. Then you just subtract both

**Comment by fenguan** [comment]
Thank you for your reply. Yes, I have got the track, what should I do if I want to count the number of occurrences of all ids. Do you have the relevant code or know where to find a way to handle it?
I tried to google it, but couldn't find it.

Finally, the first two columns should be the frame number and ID, what is behind it?
Thank you so much.
![Snipaste_2023-03-25_16-38-39](https://user-images.githubusercontent.com/50098778/227706847-acb013ba-2aa1-4b4b-87f8-60ae7386194d.png)

**Comment by fenguan** [comment]
Can the thickness of the track be changed? I found that the track became thicker and thicker
![Snipaste_2023-03-25_17-09-31](https://user-images.githubusercontent.com/50098778/227708180-dc58712b-9fa5-4e04-9906-b848623bcf2e.png)
就像这样
![Snipaste_2023-03-25_17-10-44](https://user-images.githubusercontent.com/50098778/227708311-f735d8de-b5b4-4144-8198-0d75198c19ec.png)
