### ISSUE TITLE
Where the extracted feature is saved when ReID works?

### ISSUE THREAD

**Issue by kabuto1211** [mikel-brostrom/yolov8_tracking#792]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

For building tracking across multi-cameras purpose, I need to know where the information about feature extracted by ReID model. Tks in advance.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/blob/4cc649afa9b2c0edb05dfa59fe78d8bd4667f93c/trackers/deepocsort/ocsort.py#L245
