### ISSUE TITLE
MOT evaluation index data is very low

### ISSUE THREAD

**Issue by Su12234747** [mikel-brostrom/yolov8_tracking#793]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

hi，I use yolov8 and strongsort method to verify its detection and tracking effect on MOT17-02-FRCNN video, automatically save the generated txt file, pass in the gt.txt of the video and use trackeval for calculation, but the tracking effect obtained is not good.
<img width="1142" alt="屏幕截图 2023-03-25 123313" src="https://user-images.githubusercontent.com/92658452/227696389-76426134-13dd-45e7-a0fa-9c4d6f9bdfc6.png">
<img width="252" alt="屏幕截图 2023-03-25 123617" src="https://user-images.githubusercontent.com/92658452/227696392-a9e6e2a3-2b87-4173-97fe-7e9207f8085b.png">
<img width="241" alt="屏幕截图 2023-03-25 123917" src="https://user-images.githubusercontent.com/92658452/227696450-d22df5f3-af7d-434b-aa0c-c11fd9c8458e.png">

Is there something wrong with my operation?

**Comment by mikel-brostrom** [comment]
Which model are you using? With Yolov8m you should get


```
MOT17-02-FRCNN                     33.206    24.564    45.1      25.163    84.839    46.954    86.804    86.686    33.647    38.14     83.737    31.938
```

**Comment by mikel-brostrom** [comment]
For better results you should tune the model on a people dataset such as `Crowdhuman`
