### ISSUE TITLE
Text File Format

### ISSUE THREAD

**Issue by SalmaZakaria** [mikel-brostrom/yolov8_tracking#794]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello, 
This is the structure of the result of the text file for one video.
what does each number refer to ?
![image](https://user-images.githubusercontent.com/53764024/227733806-1fc03abe-ecdb-438e-a3f1-547cd0959417.png)

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/535#issuecomment-1254562549
