### ISSUE TITLE
Tracking with Multi Non-overlapping cameras

### ISSUE THREAD

**Issue by kabuto1211** [mikel-brostrom/yolov8_tracking#795]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I want to know if this model can track object, especially person, with multi non-overlapping cameras, i.e. if one object goes from camera I to cameras II, its ID remain the same. If cannot, what can I do to fix this? Thank you.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/594
