### ISSUE TITLE
unrecognized arguments if  --source path/*

### ISSUE THREAD

**Issue by rizomus** [mikel-brostrom/yolov8_tracking#805]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

try to:
$python3 track.py --source path/*
but got 
track.py: error: unrecognized arguments: /content/drive/MyDrive/Helmet/tmp_vid/ccc.mp4

### Environment

google colab

### Minimal Reproducible Example

!python3 yolov8_tracking/track.py --yolo-weights /content/drive/MyDrive/Helmet/models/best.pt --tracking-method ocsort --source /content/drive/MyDrive/Helmet/tmp_vid/* --save-txt --save-conf --save-trajectories

**Comment by mikel-brostrom** [comment]
If you have multiple video under a folder the right way of doing this is: https://github.com/mikel-brostrom/yolov8_tracking/issues/583#issuecomment-1301791768
