### ISSUE TITLE
May I ask how to modify the program code into traffic flow calculation?

### ISSUE THREAD

**Issue by ChingIvy** [mikel-brostrom/yolov8_tracking#813]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I know how to add lines and text in the video, but I don’t know how to count the detected cars and add them after touching the line. Can someone please answer? Thank you very much!!

**Comment by mikel-brostrom** [comment]
There are many many projects out there doing this. A quick search gives me:

https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking
https://github.com/vanhaito/YOLOX-ByteTrack-Car-Counter

Use the methods in any of those
