### ISSUE TITLE
evaluating datasets

### ISSUE THREAD

**Issue by ACMaker1** [mikel-brostrom/yolov8_tracking#814]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Does this project have a module for evaluating datasets?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset
