### ISSUE TITLE
Can I use DeepOCSORT for yolov5?

### ISSUE THREAD

**Issue by YOOHYOJEONG** [mikel-brostrom/yolov8_tracking#815]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Thank you for your good research.
I've been working on tracking by referring to your repo since the name "Yolov5_StrongSORT_OSNet".

I was using OCSORT as a tracking-method with Yolov5 using the previous version of repo. However, since DeepOCSORT was recently released, I wanted to use DeepOCSORT as a tracking-method, so I visited your GitHub and it seems that there are many changes.

The source code seems to have changed to match the recently released Yolov8. And thankfully, Deep OCSORT has also been added to the tracking-method.

Therefore, I have one question.
Is there a way to use Yolov5 with a new tracking-method, DeepOCSORT, in your previous version of repository that I used before?

I want to leave the code I modified while studying and use the tracking-method as a deep OCSORT with Yolov5.

Is there any way I can do it?

Thank you.

**Comment by mikel-brostrom** [comment]
> I've been working on tracking by referring to your repo since the name "Yolov5_StrongSORT_OSNet".

:smile: 

> I want to leave the code I modified while studying and use the tracking-method as a deep OCSORT with Yolov5.

There is no easy way of achieving this. However, I would:
1. Remove the yolov8 submodule
2. Add yolov5
3. Adapt all the paths to use yolov5

**Comment by YOOHYOJEONG** [comment]
Thank you so much for your quick response.
I'll try it with the method you told me.

Thank  you :)

**Comment by mesllo** [comment]
Have you managed to implement this please?

**Comment by YOOHYOJEONG** [comment]
@mesllo Yes. I'm using it the way Mikel told me.

**Comment by lpc-eol** [comment]
> @mesllo Yes. I'm using it the way Mikel told me.
Thank you for your sharing.
I am currently working on the same purposes. Could you share more details about it? I tried to modify the track.py in v10.1, but it seems that I have to remove everything about the predictor in the programme.

**Comment by lpc-eol** [comment]
> > I've been working on tracking by referring to your repo since the name "Yolov5_StrongSORT_OSNet".
> 
> 😄
> 
> > I want to leave the code I modified while studying and use the tracking-method as a deep OCSORT with Yolov5.
> 
> There is no easy way of achieving this. However, I would:
> 
> 1. Remove the yolov8 submodule
> 2. Add yolov5
> 3. Adapt all the paths to use yolov5

I have made it. Thank you for your suggestion.
