### ISSUE TITLE
evolve评估MOT17-mini数据集报错

### ISSUE THREAD

**Issue by youzixpz** [mikel-brostrom/yolov8_tracking#817]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

大佬可以给出评估自己数据集的例子吗!KeyError: 'HOTA'[c3cda323172bb7a636e10422dade581](https://user-images.githubusercontent.com/41287125/230698584-50aa1221-e2ad-4ea4-b7a1-69b40cdbcc12.jpg)

**Comment by mikel-brostrom** [comment]
The CI pipeline tests evolve using MOT17-mini, so evolve works. What may be happening is that track eval fails for some reason, not returning the eval results. Check the logs in detail.

**Comment by fat-kid** [comment]
> 



> ### Search before asking
> * [x]  I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.
> 
> ### Question
> 大佬可以给出评估自己数据集的例子吗!KeyError: 'HOTA'[c3cda323172bb7a636e10422dade581](https://user-images.githubusercontent.com/41287125/230698584-50aa1221-e2ad-4ea4-b7a1-69b40cdbcc12.jpg)

请问一下，您解决了这个问题了吗？我也遇到了这个问题，但是我不知道怎么改。我的是说那个data下面没有文件
`Tracker file not found: D:\Downloads\yolov8_tracking\val_utils\data/trackers/mot_challenge/MOT17-mini\exp\data\MOT17-02-FRCNN.txt`
以及您这个问题，我怎么改都不能跑。。我很迷惑。。
