### ISSUE TITLE
 val.py problem

### ISSUE THREAD

**Issue by uopop** [mikel-brostrom/yolov8_tracking#818]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

when i use val.py in windows
it has error:
val: yolo_weights=yolov8/yolov8_best.pt, reid_weights=/root/autodl-tmp/yolov8_tracking/weights/osnet_x1_0_dukemtmcreid.pt, tracking_method=bytetrack, tracking_config=trackers/bytetrack/configs/bytetrack.yaml, name=exp, project=runs/val, exist_ok=False, benchmark=bird12, split=train, eval_existing=, conf_thres=0.5122620708221085, imgsz=[1280], device=[''], processes_per_device=2
/root/miniconda3/bin/python: can't open file 'val_utils/scripts/run_mot_challenge.py': [Errno 2] No such file or directory

Traceback (most recent call last):
  File "val.py", line 353, in <module>
    e.run(opt)
  File "val.py", line 304, in run
    writer.add_scalar('HOTA', combined_results['HOTA'])
KeyError: 'HOTA'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-C to quit
please tell me how can sove this problem， thank you！

**Comment by mikel-brostrom** [comment]
Check the logs. Something is crashing but you are not seeing it.

**Comment by uopop** [comment]
Sorry, I still can't solve it. Can you provide more details about the solution?
/root/miniconda3/bin/python: can't open file 'val_utils/scripts/run_mot_challenge.py': [Errno 2] No such file or directory
val_utils created  myself according to your readme,  there are no scripts in it.
thanks!

**Comment by mikel-brostrom** [comment]
You shouldn't create val_utils yourself. Run val.py, let it download the val_utils repo and then place your custom dataset in that folder as described in the wiki

**Comment by uopop** [comment]
Thank you, it has been resolved！

**Comment by fat-kid** [comment]
> Check the logs. Something is crashing but you are not seeing it.

I had met the same question, I try to run val.py and set the benchmark='MOT17-mini'.
I can get the MOT_result.txt and some mp4 files in the runs/val, but it occur that error:
`trackeval.utils.TrackEvalException: Tracker file not found: MOT17-mini/exp3\data/MOT17-02-FRCNN.txt`

`Tracker file not found: D:\code\tracking\code\yolov8_tracking-master\val_utils\data/trackers/mot_challenge/MOT17-mini\exp3\data\MOT17-02-FRCNN.txt`

`Traceback (most recent call last):
  File "D:/code/tracking/code/yolov8_tracking-master/val.py", line 369, in <module>
    e.run(opt)
  File "D:/code/tracking/code/yolov8_tracking-master/val.py", line 321, in run
    writer.add_scalar('HOTA', combined_results['HOTA'])
KeyError: 'HOTA'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit`

**Comment by mikel-brostrom** [comment]
Investigate why the .txt path contains both `/` and `\`. This repo is system agnostic as shown in the CI.
