### ISSUE TITLE
static object tracking missing problem method

### ISSUE THREAD

**Issue by YOOHYOJEONG** [mikel-brostrom/yolov8_tracking#819]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hi. Thank you very much for your help last time. Thanks to you, I was able to solve it quickly.
Thank you.

I had a question while studying.

Since the tracking algorithm is largely dependent on the performance of the detector, the tracking id is changed for static objects that repeat the occurrence and disappearance of bounding boxes for inaccurate objects.
This happens when you use strong sort as a tracking-method.

In this case, I have re-learned the detection model so that it can perform better.

However, is there any algorithm or idea that can solve this problem because I can't re-learn the detection model every time?
I would like to ask your opinion on what part of your code should be modified or added to solve this problem.

I know You wrote the code based on the strongsort paper but I was wondering if I could get your idea if it wouldn't be rude.

Thank you.

**Comment by mikel-brostrom** [comment]
I think you are facing an MLOps problem. If your scenarios is constantly changing you need some continuous training loop. This can be achieved by monitoring performance drift in the detections

**Comment by YOOHYOJEONG** [comment]
Okaaay...
I'll try.

Thank you for your answer. :)

**Comment by mikel-brostrom** [comment]
It has no easy solution, I know :cry:
