### ISSUE TITLE
No module named 'yolov8.ultralytics'

### ISSUE THREAD

**Issue by fraromesc** [mikel-brostrom/yolov8_tracking#821]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

I've just follow the instruction to install the repo. I've downloaded the repos as is said and install the requirements. I put a video called "video.mp4" on the folder of "yolov8_tracking". At this moment I didn't have any problem.  So, I tried to get the first result with yolo. 

I used the command :
` python3 track.py --source video.mp4`
And the terminal gave me this error: 
```
Traceback (most recent call last):
  File "/home/fraromesc/Documents/4I/yolov8_tracking/track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
ModuleNotFoundError: No module named 'yolov8.ultralytics'

```

I tried to install yolov8 as: 
`pip3 install yolov8`
And I installed it without problem. But the error at using this error is still there. 
I also tried: 
`pip install yolov8`
` python3 track.py --source video.mp4`

But I have the same error.

### Environment

- Ubuntu 22.04
-

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/issues/780
