### ISSUE TITLE
HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1rb8UN5ZzPKRc_xvtHlyDh-cSz88YX9hs (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

### ISSUE THREAD

**Issue by theprofessor249** [mikel-brostrom/yolov8_tracking#822]
### Search before asking

- [x] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1rb8UN5ZzPKRc_xvtHlyDh-cSz88YX9hs (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))这个问题怎么解决
![image](https://user-images.githubusercontent.com/48745598/231410374-fd65a97b-cd45-4309-bce6-9900365134b0.png)

**Comment by mikel-brostrom** [comment]
You have clearly not searched in the issues. Closing...
