### ISSUE TITLE
about deepocsort's features

### ISSUE THREAD

**Issue by Decarryee** [mikel-brostrom/yolov8_tracking#823]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

The deepocsort use `dets_embs = self._get_features(dets[:, :4], img_numpy)`  to get features. And the dets are [xyxy].
If we use
```
 def _get_features(self, bbox_xywh, ori_img):
        im_crops = []
        for box in bbox_xywh:
            x1, y1, x2, y2 = self._xywh_to_xyxy(box)
            im = ori_img[y1:y2, x1:x2]
            im_crops.append(im)
        if im_crops:
            features = self.embedder(im_crops).cpu()
        else:
            features = np.array([])
        return features
``` 
to get features, we will turn the [xyxy] to [xyxy]. 
 I think it might be wrong, could you answer my question?

**Comment by mikel-brostrom** [comment]
This looks like a bug. Thank you for reporting! Working on it

**Comment by mikel-brostrom** [comment]
Clearly a bug:

```bash
self._xywh_to_xyxy(box)
HOTA: 38.629
MOTA: 37.727
IDF1: 45.454

box.astype(int)
HOTA: 39.267
MOTA: 37.833
IDF1: 46.379
```
