### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025FEF88A4F0>: Failed to establish a new connection: [WinError 10060]

### ISSUE THREAD

**Issue by Eli15897** [mikel-brostrom/yolov8_tracking#824]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000025FEF88A4F0>: Failed to establish a new connection: [WinError 10060]

**Comment by Eli15897** [comment]
用了vpn以后就是这样
requests.exceptions.SSLError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Sentry is attempting to send 1 pending error messages

**Comment by RebornFenix** [comment]
请问这个问题解决了吗

**Comment by mikel-brostrom** [comment]
Try a VPN?

**Comment by luke110** [comment]
Using a vpn doesn't work either
