### ISSUE TITLE
classification error

### ISSUE THREAD

**Issue by ZziTaiLeo** [mikel-brostrom/yolov8_tracking#825]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hi! When I ran the demo to identify the person's movement path, I found that the background item umbrella was classified as classes=0, and the confidence level was as high as 60~70. Is this a reasonable phenomenon? I use yolov8n, reid-weights=osnet_x1_0_market.pt. While we can isolate objects with low confidence by tweaking conf-thres, it is possible to filter out some people objects with low confidence. How do I choose between them.

**Comment by mikel-brostrom** [comment]
> it is possible to filter out some people objects with low confidence

`python track.py --conf-thres XX`
