### ISSUE TITLE
Filter out classes

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/yolov8_tracking#826]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

![image](https://user-images.githubusercontent.com/108001646/232656591-e6136d17-25d7-433d-bf73-3ba95000a89f.png)

When I track people, the pedestrian still displays [head number], why is that? How can I cancel it? Looking forward to your reply!

**Comment by mikel-brostrom** [comment]
Just filter out the classes that are not head:

`python track.py --classes 0  # only people, no head`
