### ISSUE TITLE
When inputting as an image, the output result is MP4, and the result cannot be saved as an image.

### ISSUE THREAD

**Issue by Stephen-Ning** [mikel-brostrom/yolov8_tracking#829]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

As shown in the question.

**Comment by mikel-brostrom** [comment]
Just split the video into separate images. A quick search gave me this:

https://stackoverflow.com/questions/3917601/ffmpeg-split-avi-into-frames-with-known-frame-rate

**Comment by Stephen-Ning** [comment]
> 只需将视频分成单独的图像即可。快速搜索给了我这个：
> 
> https://stackoverflow.com/questions/3917601/ffmpeg-split-avi-into-frames-with-known-frame-rate

thank you! I thought this repo had this feature before, haha!

**Comment by mikel-brostrom** [comment]
You may be right... At some point I think that specifying a folder with images as input gave a folder as output
