### ISSUE TITLE
jetson xavier nx deployment issues

### ISSUE THREAD

**Issue by wangjianan-123** [mikel-brostrom/yolov8_tracking#832]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

"When deploying the yolov8s.engine model on Jetson Xavier NX, the inference speed is slower than using the yolov8s.pt model."
thanks

**Comment by mikel-brostrom** [comment]
This is a question for the official YOLOv8 repo
