### ISSUE TITLE
KeyError: 'net_dict'

### ISSUE THREAD

**Issue by vector987** [mikel-brostrom/yolov8_tracking#833]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

请问这个网络模型在哪定义的

**Comment by mikel-brostrom** [comment]
ReID models can be found here: https://github.com/mikel-brostrom/yolov8_tracking/tree/master/trackers/strongsort/deep/models
