### ISSUE TITLE
Extend StrongSort to 3 dimensions 

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/yolov8_tracking#834]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar enhancement requests.

### Description

when using a depth camera the depth  could be used to enhance the tracking as well as improve occlusion issues.

### Use case

in a retail case where people sometimes stand in place for some time this might significantly improve metrics

**Comment by mikel-brostrom** [comment]
Won't do, RGB is the source for this repo. Don't have resources nor time for this
