### ISSUE TITLE
TypeError: non_max_suppression() got an unexpected keyword argument 'nm'

### ISSUE THREAD

**Issue by Crear12** [mikel-brostrom/yolov8_tracking#835]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I downloaded the latest Yolov8 from the embed link, in the latest code, it only takes max_nms, there's no argument names "nm". I assume that the track.py needs an update?

Latest non_max_suppression from ops.py is attached:
def non_max_suppression(
        prediction,
        conf_thres=0.25,
        iou_thres=0.45,
        classes=None,
        agnostic=False,
        multi_label=False,
        labels=(),
        max_det=300,
        nc=0,  # number of classes (optional)
        max_time_img=0.05,
        max_nms=30000,
        max_wh=7680,
):

### Environment

https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/ops.py

### Minimal Reproducible Example

python track.py --source "a.mp4"  --save-crop --save-vid --device 0 --yolo-weights yolov8n-seg.pt

**Comment by Jxzde** [comment]
I have the same problem, did you solve it please? Thank you very much! @Crear12

**Comment by chenyd0763** [comment]
I also have the same issue with this when I tried to run a segmentation task. Btw my ultralytics version is 8.0.88.

**Comment by mikel-brostrom** [comment]
Follow the installation instructions please. You have an ultralytics version that does not match the one in this repo
