### ISSUE TITLE
I'm having problems installing environment dependencies

### ISSUE THREAD

**Issue by happy-miaomiao** [mikel-brostrom/yolov8_tracking#837]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I'm having trouble installing environment dependencies,Can you give some advice? Thank you very much.

Building wheels for collected packages: lap
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Partial import of lap during the build process.
      C:\Users\Dell\AppData\Local\Temp\pip-install-ehw7d9nw\lap_33333b777b4242dfbdc1e4c812cd1a22\setup.py:223: DeprecationWarning:
     
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
     
     
        from numpy.distutils.core import setup
      Generating cython files
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      D:\Anaconda3\envs\yourEnv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use buil
d and pip and other standards-based tools.
        warnings.warn(
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lap
      copying lap\lapmod.py -> build\lib.win-amd64-cpython-38\lap
      copying lap\__init__.py -> build\lib.win-amd64-cpython-38\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1077] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-buil
d-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\Dell\AppData\Local\Temp\pip-install-ehw7d9nw\lap_33333b777b4242dfbdc1e4c812cd1
a22\build\temp.win-amd64-cpython-38\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
Failed to build lap

**Comment by mikel-brostrom** [comment]
Cannot recommend using anaconda. Never tried it and is not official supported by the repo. Just try pip
