### ISSUE TITLE
Using a feature extractor that is pre-trained on a non-ReID dataset like COCO.

### ISSUE THREAD

**Issue by mesllo-bc** [mikel-brostrom/yolov8_tracking#838]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I see that the feature extractor weights point to models such as OSNet and ResNet that were pre-trained on MOT17. Is it possible to specify a model that was pre-trained on some other task like OD on COCO, and are there any changes that need to be made?

Thanks!

**Comment by mikel-brostrom** [comment]
No, they were not pretrained on MOT17. They are pretrained on whatever dataset name follows the model name in this file:

https://github.com/mikel-brostrom/yolov8_tracking/blob/master/trackers/strongsort/deep/reid_model_factory.py
