### ISSUE TITLE
Evaluation of tracking indicators

### ISSUE THREAD

**Issue by yaozenghui** [mikel-brostrom/yolov8_tracking#843]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Error reported when running program val.py: FileNotFoundError: [Errno 2] No such file or directory: 'runs\\val\\exp\\MOT_results.txt'

**Comment by mikel-brostrom** [comment]
Have you checked why that file isn't there? Check why `track.py` is failing

**Comment by yaozenghui** [comment]
> Have you checked why that file isn't there? Check why `track.py` is failing

The track.py file can run normally, but the val.py file reported an error when running. I always fail when running the tool for generating evaluations using the val.py file. Could you please provide the complete code for the evaluation and the complete file under the val_utils file. Thank you very much! This is my email yaozenghui2020@163.com

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset

**Comment by yaozenghui** [comment]
> https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset

I have tried following your steps, but failed in the first step (Run once in order to download the evaluation toolsval.py). I would greatly appreciate it if you could provide the complete val_utils file. Thank you very much! This is my email yaozenghui2020@163.com

**Comment by yaozenghui** [comment]
This is my complete error report:
val: yolo_weights=./weights/yolov8x.pt, reid_weights=./weights/osnet_x1_0_msmt17_256x128.pt, tracking_method=strongsort, tracking_config=trackers\strongsort\configs\strongsort.yaml, name=exp, project=runs\val, exist_ok=False, benchmark=MOT17, split=test, eval_existing=, conf_thres=0.5122620708221085, imgsz=[640], device=[''], processes_per_device=2
Eval repo already downloaded
val: yolo_weights=./weights/yolov8x.pt, reid_weights=./weights/osnet_x1_0_msmt17_256x128.pt, tracking_method=strongsort, tracking_config=trackers\strongsort\configs\strongsort.yaml, name=exp, project=runs\val, exist_ok=False, benchmark=MOT17, split=test, eval_existing=, conf_thres=0.5122620708221085, imgsz=[640], device=[''], processes_per_device=2
usage: run_mot_challenge.py [-h] [--USE_PARALLEL USE_PARALLEL]
                            [--NUM_PARALLEL_CORES NUM_PARALLEL_CORES]
                            [--BREAK_ON_ERROR BREAK_ON_ERROR]
                            [--RETURN_ON_ERROR RETURN_ON_ERROR]
                            [--LOG_ON_ERROR LOG_ON_ERROR]
                            [--PRINT_RESULTS PRINT_RESULTS]
                            [--PRINT_ONLY_COMBINED PRINT_ONLY_COMBINED]
                            [--PRINT_CONFIG PRINT_CONFIG]
                            [--TIME_PROGRESS TIME_PROGRESS]
                            [--DISPLAY_LESS_PROGRESS DISPLAY_LESS_PROGRESS]
                            [--OUTPUT_SUMMARY OUTPUT_SUMMARY]
                            [--OUTPUT_EMPTY_CLASSES OUTPUT_EMPTY_CLASSES]
                            [--OUTPUT_DETAILED OUTPUT_DETAILED]
                            [--PLOT_CURVES PLOT_CURVES]
                            [--GT_FOLDER GT_FOLDER]
                            [--TRACKERS_FOLDER TRACKERS_FOLDER]
                            [--OUTPUT_FOLDER OUTPUT_FOLDER [OUTPUT_FOLDER ...]]
                            [--TRACKERS_TO_EVAL TRACKERS_TO_EVAL [TRACKERS_TO_EVAL ...]]
                            [--CLASSES_TO_EVAL CLASSES_TO_EVAL [CLASSES_TO_EVAL ...]]
                            [--BENCHMARK BENCHMARK]
                            [--SPLIT_TO_EVAL SPLIT_TO_EVAL]
                            [--INPUT_AS_ZIP INPUT_AS_ZIP]
                            [--DO_PREPROC DO_PREPROC]
                            [--TRACKER_SUB_FOLDER TRACKER_SUB_FOLDER]
                            [--OUTPUT_SUB_FOLDER OUTPUT_SUB_FOLDER]
                            [--TRACKER_DISPLAY_NAMES TRACKER_DISPLAY_NAMES [TRACKER_DISPLAY_NAMES ...]]
                            [--SEQMAP_FOLDER SEQMAP_FOLDER [SEQMAP_FOLDER ...]]
                            [--SEQMAP_FILE SEQMAP_FILE [SEQMAP_FILE ...]]
                            [--SEQ_INFO SEQ_INFO [SEQ_INFO ...]]
                            [--GT_LOC_FORMAT GT_LOC_FORMAT]
                            [--SKIP_SPLIT_FOL SKIP_SPLIT_FOL]
                            [--METRICS METRICS [METRICS ...]]
                            [--THRESHOLD THRESHOLD]
run_mot_challenge.py: error: argument --SEQ_INFO: expected at least one argument

Traceback (most recent call last):
  File "E:/yolov8_tracking/val.py", line 353, in <module>
    e.run(opt)
  File "E:/yolov8_tracking/val.py", line 298, in run
    results = e.eval(opt, seq_paths, save_dir, MOT_results_folder, val_tools_path, gt_folder, free_devices)
  File "E:/yolov8_tracking/val.py", line 255, in eval
    with open(save_dir / 'MOT_results.txt', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'runs\\val\\exp\\MOT_results.txt'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit

**Comment by mikel-brostrom** [comment]
> I have tried following your steps, but failed in the first step (Run once in order to download the evaluation toolsval.py).

Use a VPN
