### ISSUE TITLE
StrongSORT speed(fps) issue

### ISSUE THREAD

**Issue by YOOHYOJEONG** [mikel-brostrom/yolov8_tracking#844]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hi.

I happened to see the issue(https://github.com/NirAharon/BoT-SORT/issues/42) you left in the past.

And... I had a question when I saw your issue.
When I use yolov5+strongsort, it doesn't come up to the fps you wrote down(~20fsp).

It takes yolov5s-0.006s and tracking(strongsort)-0.05s per frame, resulting in a total of 0.06s per frame.
So, I can only get up to 16fps.(It's also slower than this.)
(Same fps when yolov8 is used.)

I have at least 20 objects in a frame, is it because of the large number of objects?

Is there anything I'm missing?

Thank you.

**Comment by mikel-brostrom** [comment]
There are many aspects to this. Image size and number of detected objects  as well as GPU are relevant for the inference speed of the whole system. It is not a fixed 20 FPS for all cases

**Comment by YOOHYOJEONG** [comment]
Oh, Thank you.

I checked the things you said.
I must have been missing something really basic.

Thank you for your answer. :)
