### ISSUE TITLE
How do we add feature extraction to ByteTrack?

### ISSUE THREAD

**Issue by mesllo-bc** [mikel-brostrom/yolov8_tracking#846]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I notice that this option is possible in StrongSORT but not for ByteTrack. The paper states that this should be possible. Is there a way we can do this on this repo, please? Thank you!

**Comment by mikel-brostrom** [comment]
Checkout DeepOCSORT and try to make the same modification. But, it is not trivial how to fuse motion and appearance information...
