### ISSUE TITLE
an error occur while run val.py 

### ISSUE THREAD

**Issue by fat-kid** [mikel-brostrom/yolov8_tracking#847]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Firstly, I had found the same question in the issues #818 and #817, I also comment in these two issue, but no reply, so I try to create an new isuue.
I have try to modify the benchmark to MOT17 and MOT17-mini, the first one can downloaded the dataset(this means that I can use my VPN to get the datasets, so there it is no network problem) , unziped it and get the results(some mp4 files, yaml files and MOT_results.txt) in the runs\val\exp5, and then it occur an error whilt the program try to val,
`Traceback (most recent call last):
  File "val_utils\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "D:\code\tracking\code\yolov8_tracking-master\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 126, in __init__
    curr_file))
trackeval.utils.TrackEvalException: Tracker file not found: MOT17/exp5\data/MOT17-02-FRCNN.txt`

This is my MOT_results.txt
`
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : D:\code\tracking\code\yolov8_tracking-master\val_utils\error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : val_utils\data\MOT17\train    
TRACKERS_FOLDER      : D:\code\tracking\code\yolov8_tracking-master\val_utils\data/trackers/mot_challenge/
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['MOT17']                     
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : MOT17                         
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : exp5\data                     
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOT17-02-FRCNN': None, 'MOT17-04-FRCNN': None, 'MOT17-05-FRCNN': None, 'MOT17-09-FRCNN': None, 'MOT17-10-FRCNN': None, 'MOT17-11-FRCNN': None, 'MOT17-13-FRCNN': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: D:\code\tracking\code\yolov8_tracking-master\val_utils\data/trackers/mot_challenge/MOT17\exp5\data\MOT17-02-FRCNN.txt
[0m`

The similar question had met, while the benchmark is MOT17-mini, i feel confuse about how to deal with it, I would appreciate it if you could give me some solutions！！！

**Comment by fat-kid** [comment]
it seems there are something wrong when I download yolov8 by zip, but when I try to use
`git clone --recursive https://github.com/mikel-brostrom/yolov8_tracking.git`
and try to run the val.py, it runs successfully！！！

**Comment by mikel-brostrom** [comment]
When downloading the repo as zip the submodules are not initialized
