### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'stride', when I run track.py

### ISSUE THREAD

**Issue by lynxhawk** [mikel-brostrom/yolov8_tracking#848]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

![BTTQ~ `FP 9WA5E $HLZ_MV](https://user-images.githubusercontent.com/26079070/237051439-9f91c9f9-5cd2-4115-9d28-ea17e64c14c2.png)
When i run track.py, i met this problem. 
My best.pt can predict detections, but it can not track. I have no idea to solve this problem.

**Comment by mikel-brostrom** [comment]
I see you use the 8.0.94 version of the Ultralyticsrepo. This is not supported. Stick to what supported

**Comment by lynxhawk** [comment]
Thank you! I didn't notice the problem.
