### ISSUE TITLE
Tensorrt ReID model crashes when input batch size is larger than one 

### ISSUE THREAD

**Issue by tfidmmatthew** [mikel-brostrom/yolov8_tracking#851]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

[TensorRT] ERROR: 3: [executionContext.cpp::setBindingDimensions::969] Error Code 3: Internal Error (Parameter check failed at: runtime/api/executionContext.cpp::setBindingDimensions::969, condition: profileMaxDims.d[i] >= dimensions.d[i]. Supplied binding dimension [2,3,256,128] for bindings[0] exceed min ~ max range at index 0, maximum dimension in profile is 1, minimum dimension in profile is 1, but supplied dimension is 2.

I tried with osnet_x0_25_msmt17.engine model, and it only crashed occasionally on some videos. I run the same videos with osnet_x0_25_msmt17.pt and it works

<img width="1385" alt="圖片" src="https://github.com/mikel-brostrom/yolov8_tracking/assets/101381540/cfdf7e07-d7f2-4270-8859-e29138876e8e">

### Environment

YOLOv5 🚀 v7.0-0-g915bbf2 Python-3.8.12 torch-1.10.0a0+0aef44c CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11178MiB)
strongsort

**Comment by mikel-brostrom** [comment]
Please provide the full export command. Otherwise I won't be able to help you

**Comment by mikel-brostrom** [comment]
I can see that it fails when you input has a batch size more than 1 so I suppose you didn't export the model with dynamic axes. Try this:

```bash
python3 trackers/reid_export.py --include engine --device 0 --batch-size 16 --dynamic --workspace 40
```

**Comment by mikel-brostrom** [comment]
As batch size is default one:

https://github.com/mikel-brostrom/yolov8_tracking/blob/4f8aeb337aa367803222b801b7561538dccf5bb2/trackers/reid_export.py#L243

Your exported model only works for inputs with batch size one.

**Comment by tfidmmatthew** [comment]
Resolved, thanks for you quick help
