### ISSUE TITLE
Local variable 'checkpoint' referenced before assignment.

### ISSUE THREAD

**Issue by hungnt14** [mikel-brostrom/yolov8_tracking#856]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

![image](https://github.com/mikel-brostrom/yolov8_tracking/assets/33962566/dae0658f-59ef-4c89-92df-a745f6b19c76)

### Environment

- Ultralytics YOLOv8.0.54 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA T4, 16Gb VRAM)
- Strongsort
### Minimal Reproducible Example

```
python3 track.py --tracking-method strongsort  \
    --source sample.mp4 \
    --yolo-weights yolov8m.pt \
    --img 640 \
    --save-vid
```

**Comment by hungnt14** [comment]
I think the problem come from this [line](https://github.com/mikel-brostrom/yolov8_tracking/blob/master/trackers/strongsort/deep/reid_model_factory.py#L183) of code. If the we use CUDA, the `checkpoint` variable won't be initialized. Please check that again.

**Comment by H3linAx** [comment]
I have same issue.

Ultralytics YOLOv8.0.20  Python-3.8.16 torch-2.0.1+cu118 CUDA:0 (NVIDIA GeForce RTX 3070, 8192MiB) on window 10

I think if cuda is on, then checkpoint is undefined. That lead us to same error.

**Comment by hungnt14** [comment]
> Let me know if this works @H3linAx, @hungnt14 😄

This worked smoothly to me.

**Comment by H3linAx** [comment]
> Let me know if this works @H3linAx, @hungnt14 😄

WORKS! Thanks!
