### ISSUE TITLE
yolov8 pos

### ISSUE THREAD

**Issue by StormS0** [mikel-brostrom/yolov8_tracking#857]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar enhancement requests.

### Description

https://docs.ultralytics.com/tasks/pose/#train
Can you support this pose model?

**Comment by mikel-brostrom** [comment]
Thanks for the suggestion. I need to do a proper refactor anyways based on all the new Yolov8 features. That is next on the roadmap for me :smile:
