### ISSUE TITLE
Custom dataset format questions

### ISSUE THREAD

**Issue by ACMaker1** [mikel-brostrom/yolov8_tracking#858]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

MOTCUSTOM
├── test
│   ├── MOTCUSTOM-01          # the content of all the sequence folders should be the same
│   │   ├── img1
│   │   │    ├── 000001.jpg
│   │   │    ├── 000002.jpg
│   │   │    ├── ...
│   │   │    └── XXXXXX.jpg
│   │   ├── gt
│   │   │   └── gt.txt
│   │   └── seqinfo.ini
│   ├── MOTCUSTOM-02
│   ├── ...
│   └── MOTCUSTOM-05
└── train
    ├── MOTCUSTOM-06
    ├── ...
    └── MOTCUSTOM-10

（1）Can the content format of img1 be 00000001.png?

（2）Are there any requirements for the content format of GT.txt?

**Comment by mikel-brostrom** [comment]
> Can the content format of img1 be 00000001.png?

 Yes

> Are there any requirements for the content format of GT.txt?

Just mimic the output txt format :smile:

**Comment by ACMaker1** [comment]
Whether the image is the original or labeled？

**Comment by ACMaker1** [comment]
I want to evaluate my own dataset, but don't know how to generate det.txt and gt.txt files, is there any way
