### ISSUE TITLE
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package

### ISSUE THREAD

**Issue by camongman** [mikel-brostrom/yolov8_tracking#859]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I've installed it as your instructions.
I understand that yolov8 version that I need is 8.0.20.
I've confirmed that version is installed right way..

'''
git clone --recurse-submodules https://github.com/mikel-brostrom/yolov8_tracking.git  # clone recursively
cd yolov8_tracking
pip install -r requirements.txt  # install dependencies
'''

And I've trained object detection and reid models with the custom dataset. 
But, I got an error like below when I run track.py file..

track: yolo_weights=[PosixPath('runs/detect/train15/weights/best.pt')], reid_weights=weights/reid_icebar_230509.pth, tracking_method=deepocsort, tracking_config=trackers/deepocsort/configs/deepocsort.yaml, source=./icebar.mp4, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_trajectories=False, save_vid=True, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False
Ultralytics YOLOv8.0.20 🚀 Python-3.8.10 torch-2.1.0a0+fe05266 CUDA:0 (NVIDIA GeForce RTX 2080 Ti, 11264MiB)
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
requirements: ❌ AutoUpdate skipped (offline)
Traceback (most recent call last):
  File "track.py", line 365, in <module>
    main(opt)
  File "track.py", line 360, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 104, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "/workspace/yolov8_tracking2/yolov8/ultralytics/nn/autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 348, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/nn/tasks.py", line 340, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 811, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1174, in _load
    result = unpickler.load()
  File "/usr/local/lib/python3.8/dist-packages/torch/serialization.py", line 1167, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

**Comment by camongman** [comment]
I'm in the middle of taking care of it with another way.

**Comment by Myguely** [comment]
Any updates? Im having the same issue

**Comment by hungnt14** [comment]
Are you using a weight file that has been trained on (maybe) latest Yolov8. I also got this issue while using that type of weight. I have to train using the version of YoloV8 that currently `yolov8_tracking` is running on and it works.

**Comment by mikel-brostrom** [comment]
I am updating the whole repo. The Yolov8 submodule will be deleted only the package will be used. Hang on a bit more :smile:

**Comment by Myguely** [comment]
Thanks, I managed to fix it by changing the imports inside the yolo module for anyone having the same issue as I.
![image](https://github.com/mikel-brostrom/yolov8_tracking/assets/58893390/1779cc1c-021f-40e0-b95c-4fe5bd01b647)

**Comment by rickkk856** [comment]
@Myguely @mikel-brostrom 

I'm facing the same issue, on branch v9.0 of this repo.

Does anyone know if there is any [ultralytics version](https://pypi.org/project/ultralytics/8.0.117/#history) that is compatible with the v9.0 of this repo besides ultralytics 8.0.20.

PS: The model i'm trying to run was trained on ultralytics 8.0.117 (latest).
By the way I'm using the v9.0 because of the csv output format which is much better for what I need.



If not I think the only workaround I can do is what @hungnt14 suggested: Retrain the model 😢 

Similar issues: 
[#864](https://github.com/mikel-brostrom/yolo_tracking/issues/864)
[ultralytics-#2573](https://github.com/ultralytics/ultralytics/issues/2573)

**Comment by mikel-brostrom** [comment]
Just use the latest version of the repo @rickkk856 :smile:

**Comment by rickkk856** [comment]
> Just use the latest version of this repo @rickkk856 😄

I tried but I was facing so many issues with this on colab that went back to the previous versions and faced other errors haha. 
Would you have an updated test version of this [GoogleColab](https://colab.research.google.com/drive/18nIqkBr68TkK8dHdarxTco6svHUJGggY?usp=sharing) notebook ?

**Comment by mikel-brostrom** [comment]
Colab got updated :smile:
