### ISSUE TITLE
can't open file 'val_utils\scripts\run_mot_challenge.py': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Jxzde** [mikel-brostrom/yolov8_tracking#862]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

When I run val.py, I encounter the error:can't open file 'val_utils\scripts\run_mot_challenge.py': [Errno 2] No such file or directory. do I need to download this file myself?

**Comment by mikel-brostrom** [comment]
Everything gets downloaded automatically when running `val.py`. Check that the downloads are not failing for whatever reason
