### ISSUE TITLE
Error running python track.py --source 0 --yolo-weights yolov8n.pt

### ISSUE THREAD

**Issue by aini0105** [mikel-brostrom/yolov8_tracking#863]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

The following error occurs when I run track.py. May I ask how to solve this problem?

Traceback (most recent call last):
  File "G:\PyCharm\pythonProject3\safe\yolov8-tracking\track.py", line 32, in <module>
    from yolov8.ultralytics.nn.autobackend import AutoBackend
ModuleNotFoundError: No module named 'yolov8.ultralytics'

**Comment by mikel-brostrom** [comment]
Search before asking https://github.com/mikel-brostrom/yolov8_tracking/issues/780
