### ISSUE TITLE
Cannot use a custom yolov8 weights

### ISSUE THREAD

**Issue by Myguely** [mikel-brostrom/yolov8_tracking#864]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I tried the naming according to the model as suggested in one of the issues but it doesn't seem to work. If I simply run `python track.py --yolo-weights yolov8s.pt` it works fine. But if I try with custom weights , like best.pt or yolov8s_best.pt I get this error.
`track: yolo_weights=[WindowsPath('yolov8s_best.pt')], reid_weights=C:\Users\35193\Desktop\TCode\yolov8_tracking\weights\lmbn_n_cuhk03_d.pt, tracking_method=deepocsort, tracking_config=trackers\deepocsort\configs\deepocsort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_trajectories=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=exp, exist_ok=False, line_thickness=2, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False, vid_stride=1, retina_masks=False
requirements: YOLOv8 requirement "lap" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Partial import of lap during the build process.
      C:\Users\35193\AppData\Local\Temp\pip-install-mf16s_or\lap_ca2b53a7d91e4506b164de4842009d63\setup.py:223: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html

        from numpy.distutils.core import setup
      Generating cython files
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\lap
      copying lap\lapmod.py -> build\lib.win-amd64-cpython-310\lap
      copying lap\__init__.py -> build\lib.win-amd64-cpython-310\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\35193\AppData\Local\Temp\pip-install-mf16s_or\lap_ca2b53a7d91e4506b164de4842009d63\build\temp.win-amd64-cpython-310\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
ERROR: Could not build wheels for lap, which is required to install pyproject.toml-based projects
requirements:  Command 'pip install "lap"  ' returned non-zero exit status 1.
Ultralytics YOLOv8.0.20  Python-3.10.11 torch-1.11.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3070 Laptop GPU, 8192MiB)
requirements: YOLOv8 requirement "ultralytics.nn.modules.conv" not found, attempting AutoUpdate...
ERROR: Could not find a version that satisfies the requirement ultralytics.nn.modules.conv (from versions: none)
ERROR: No matching distribution found for ultralytics.nn.modules.conv
requirements:  Command 'pip install "ultralytics.nn.modules.conv"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Users\35193\Desktop\TCode\yolov8_tracking\track.py", line 365, in <module>
    main(opt)
  File "C:\Users\35193\Desktop\TCode\yolov8_tracking\track.py", line 360, in main
    run(**vars(opt))
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\35193\Desktop\TCode\yolov8_tracking\track.py", line 104, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "C:\Users\35193\Desktop\TCode\yolov8_tracking\yolov8\ultralytics\nn\autobackend.py", line 74, in __init__
    model = attempt_load_weights(weights if isinstance(weights, list) else w,
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ultralytics\nn\tasks.py", line 348, in attempt_load_weights
    ckpt = torch_safe_load(w)  # load ckpt
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ultralytics\nn\tasks.py", line 340, in torch_safe_load
    return torch.load(file, map_location='cpu')  # load
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 1046, in _load
    result = unpickler.load()
  File "C:\Users\35193\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\serialization.py", line 1039, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package
Sentry is attempting to send 1 pending events
Waiting up to 2 seconds
Press Ctrl-Break to quit`

**Comment by Myguely** [comment]
I manage to solve the issue updating several imports from the yolo library 
![image](https://github.com/mikel-brostrom/yolov8_tracking/assets/58893390/98fc29e2-d466-4a80-b14a-0ad2658c6133)

**Comment by mikel-brostrom** [comment]
I am working on a complete refactor that solves all this. Give a few more days :smile:

**Comment by vhuard** [comment]
it is working on my side with custom model.
since yesterday, you have changed the names --yolo-weigths becoming --yolo-model and so on
i don't see anymore the save-trajectories option.
is it still working?

**Comment by mikel-brostrom** [comment]
`--save-trajectories` is not available atm. But all the args have now been updated in the README
