### ISSUE TITLE
Evaluation in Colab is not working

### ISSUE THREAD

**Issue by Hunter-v1** [mikel-brostrom/yolov8_tracking#865]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Evaluation

### Bug

> The error is as shown below and it appeared for the 3rd consecutive time!

Tracker file not found: /content/yolov8_tracking/val_utils/data/trackers/mot_challenge/MOTCUSTOM/exp4/data/MOTCUSTOM-04.txt

> Another problem is that whenever i move the MOTCUSTOM-04 (for example) the val.py generate this error 

Eval repo already downloaded
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 816, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'val_utils/data/MOTCUSTOM/test/.ipynb_checkpoints/img1' -> 'val_utils/data/MOTCUSTOM/test/.ipynb_checkpoints/.ipynb_checkpoints'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/content/yolov8_tracking/val.py", line 353, in <module>
    e.run(opt)
  File "/content/yolov8_tracking/val.py", line 298, in run
    results = e.eval(opt, seq_paths, save_dir, MOT_results_folder, val_tools_path, gt_folder, free_devices)
  File "/content/yolov8_tracking/val.py", line 201, in eval
    shutil.move(str(src_seq_path), str(dst_seq_path))
  File "/usr/lib/python3.10/shutil.py", line 836, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'val_utils/data/MOTCUSTOM/test/.ipynb_checkpoints/img1'
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit

### Environment

Setup complete. Using torch 2.0.0+cu118 (Tesla T4)

**Comment by mikel-brostrom** [comment]
Interesting, I have never tried to run `val.py` in colab. Will look at it at some point but it is not my prio right now

**Comment by Hunter-v1** [comment]
so u re saying that the problem may be due to the execution environment and not with the code itself ?

**Comment by mikel-brostrom** [comment]
Yes, the CI shows everything works as it should. This is, when you run it locally.

**Comment by Hunter-v1** [comment]
thank u

**Comment by mikel-brostrom** [comment]
Ok, this is next after the big refactor I just released

**Comment by Hunter-v1** [comment]
Thank u! But I m still struggling with the track process for val.py. I want to escape track and evaluate on my gt and det folders!
