### ISSUE TITLE
reset the tracker in realtime

### ISSUE THREAD

**Issue by StormS0** [mikel-brostrom/yolov8_tracking#867]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

hello,what should i do to reset the tracker in realtime. for example press R key to reset the track and let the id start from 1.

**Comment by mikel-brostrom** [comment]
It should be relatively easy. Just reset this variable on a key press

https://github.com/mikel-brostrom/yolov8_tracking/blob/6f2450204461f4c8ba776cb8933391e56871e1f9/trackers/deepocsort/ocsort.py#L351

**Comment by StormS0** [comment]
thanks.         elif cv2.waitKey(1) == ord('c'):  
                    tracker_list[i].tracker.tracks = []
                    tracker_list[i].tracker._next_id = 1

It works fine

**Comment by mikel-brostrom** [comment]
Nice!
