### ISSUE TITLE
import cv2 No module named 'cv2'

### ISSUE THREAD

**Issue by swloo618** [mikel-brostrom/yolov8_tracking#869]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I run the project in PyCharm terminal with script below and it's work fine

    python track.py --source 0 --device 0 --show-vid --tracking-method strongsort

When I run the same script using Windows Power Shell, it gave me an error 

Traceback (most recent call last):
  File "track.py", line 2, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

I check in PyCharm and Power Shell, the library is the same.  Why this will happen?

**Comment by mikel-brostrom** [comment]
You have either not loaded the right environment or not installed `opencv-python`
