### ISSUE TITLE
Can object tracking improve object detection?

### ISSUE THREAD

**Issue by spirka3** [mikel-brostrom/yolov8_tracking#870]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Can object tracking output better detections compared to pure object detector (yolov8, without tracking algorithm)?

I tried an experiment and the result is that object tracking detects 1400 objects and when I put the same video to the object detector  I got 2200 objects. Does it mean that the arguments weren't the same or that object tracking somehow improves accuracy?

**Comment by spirka3** [comment]
I see, the lower number of detections makes sense. Is there a case where the tracking algorithm could retain a detection that would otherwise not be saved?

**Comment by mikel-brostrom** [comment]
Nope, I cannot think of any edge case where this would be the case. 

However, with tracking you could predict where the object is during occlusion. This is something that an object detection model cannot do. But this is a different discussion.

**Comment by spirka3** [comment]
Thank you very much <3
