### ISSUE TITLE
YOLOv5 models

### ISSUE THREAD

**Issue by wangjianan-123** [mikel-brostrom/yolov8_tracking#871]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

1.Could you provide YOLOv5 models trained on MOT17 or Crowdhuman datasets?
2.I got the yolov5m.pt trained on the crowdhuman in the github, but i can't use it.Does the project only supports yolov5xu,yolov5mu?

**Comment by mikel-brostrom** [comment]
> Does the project only supports yolov5xu,yolov5mu?

Yes, that is right. And sadly I have no time train U models 😪
