### ISSUE TITLE
Class tracking is lost after 2 frames

### ISSUE THREAD

**Issue by vhuard** [mikel-brostrom/yolov8_tracking#873]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

i have tried to track a crossing road situation with models trained (based on yolov8m.yaml) on custom dataset with several classes including car, motorcycle,...
it was working on previous commit (May 9) which was working well and showing trajectories
in today's trial on the most recent commit, the first two frames were ok with right classes but no more trajectories
starting the third frame, all elements were classified as bicycles (even obvious cars or trucks)
any idea?

**Comment by mikel-brostrom** [comment]
This was fixed today here: https://github.com/mikel-brostrom/yolov8_tracking/pull/875
