### ISSUE TITLE
deepocsort tracker not listening to config variables

### ISSUE THREAD

**Issue by faizelkDatapost** [mikel-brostrom/yolov8_tracking#874]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I am using deepocsort as the tracking method 
configs directory
```
trackers/deepocsort/configs/deepocsort.yaml
```

My problem is that the tracking ID is kept alive for a very long time before it is removed

So I thought the solution would be, to decrease the **max_age** variable from the current value of 50 to maybe 5 for example but decreasing this value still does not make any difference

Scenario to reproduce
```
1. be visible on frame (you get a tracking ID)
2. move out of frame ( for 30 seconds)
3. move back in frame after 30 seconds and you will still have same tracking ID
```
This is the problem , you can't control using **max_age** value, the tracking ID needs to change
  when come back in frame depending on the value of **max_age**

**Comment by mikel-brostrom** [comment]
Several cameras covering the tracking area from different perspectives usually helps a lot

**Comment by faizelkDatapost** [comment]
no, so I think you misunderstanding me. The problem is that the ID is **not** lost at all. I want the ID to be lost

**Comment by faizelkDatapost** [comment]
the ID must be lost when the max_age is reached but it is not losing the ID no matter what you change the max_age value to

**Comment by mikel-brostrom** [comment]
Alright. Will have a look at it

**Comment by faizelkDatapost** [comment]
Thanks, however strongsort config works

**Comment by mikel-brostrom** [comment]
Hmmm. I am double checked in master. This:

https://github.com/mikel-brostrom/yolov8_tracking/blob/aeaf43eceb762404aff95aeaa006379c4dcff3c5/trackers/multi_tracker_zoo.py#L67C10-L80

look alright.

I have a hard time seeing how this cannot be working

**Comment by mikel-brostrom** [comment]
Sorry, but this is working.

Added `print(f'pop track {i} {trk.time_since_update}')` before: 

https://github.com/mikel-brostrom/yolov8_tracking/blob/aeaf43eceb762404aff95aeaa006379c4dcff3c5/trackers/deepocsort/ocsort.py#L516

With only me on the camera and then covering it I get:

`pop track 1 51`
