### ISSUE TITLE
Apply for license plate recognition system

### ISSUE THREAD

**Issue by leviethung2103** [mikel-brostrom/yolov8_tracking#887]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I want to apply the yolov8 detection and tracking algorithm to the License Plate Recognition Project. However, I dont want to use the ReID model. Could I change the code to disable the ReiD module? Thank you

**Comment by mikel-brostrom** [comment]
The default tracking method is deepocsort. Just select ocsort if you want it without reid.
