### ISSUE TITLE
Can I only use the detection results for the track and eval?

### ISSUE THREAD

**Issue by fat-kid** [mikel-brostrom/yolov8_tracking#892]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Modifing the yolov5/v8 is not easy for me because of its highly integrated code and it's still not stable, so I wonder if I can only use the result which generated by my modified yolov5 in the old version like yolov5-7.0 in the yolov8_tracking. Because it contain many models and eval ways which i need. 
If possible, please give me some advice or comments. Thanks a lot!

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset

**Comment by mikel-brostrom** [comment]
You can still evaluate old results following the wiki above :smile:

**Comment by fat-kid** [comment]
I try in use the weight that I train in the yolov5-7.0, and use it in the val.py. It can get the eval reuslt of tracking, but there are some error while running val.py ( `[There are not module name 'models'](requirements: YOLOv8 requirement "models" not found, attempting AutoUpdate...)` and `ModuleNotFoundError: No module named 'models')` and its eval results were worse than the yolo weight I train in the ultralytics framework. 
and I try the yolo weight I train in the ultralytics framework, there will have the detect procedure. 
when I try the modified weight again, it can't generate the result...T-T

**Comment by mikel-brostrom** [comment]
I recommend you to start from a clean slate. Reclone the repo, A LOT changed since v5 tracking. Use val.py in the newly cloned repo and point to your old results under the v5 repo.

**Comment by fat-kid** [comment]
ok, let me try it first.

**Comment by fat-kid** [comment]
sad for the error that `TypeError: ERROR ❌️ /root/yolov5/runs/train/exp5/weights/best.pt appears to be an Ultralytics YOLOv5 model originally trained with https://github.com/ultralytics/yolov5.
This model is NOT forwards compatible with YOLOv8 at https://github.com/ultralytics/ultralytics.
Recommend fixes are to train a new model using the latest 'ultralytics' package or to run a command with an official YOLOv8 model, i.e. 'yolo predict model=yolov8n.pt'`
It seems that I still need to modify yolov5 in the ultralytics  and get the weight in this framework, then use it in the val.py.

**Comment by mikel-brostrom** [comment]
> so I wonder if I can only use the result which generated by my modified yolov5 in the old version like yolov5-7.0 in the yolov8_tracking

Yes, this is a known issue, the old Yolov5 model are not usable in `Ultralytics`. You will sadly need to train them once again. The txt results can be evaluated though.

**Comment by fat-kid** [comment]
I found I can modified the yolov8->yolov5, just refer to the yolov5-DeepSort_OSNet, the version release before, it means that I can modified yolov5 simply.
