### ISSUE TITLE
How to train custom's ReID dataSet

### ISSUE THREAD

**Issue by NVRGUP** [mikel-brostrom/yolov8_tracking#894]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Whether this project can train owner ReID dataset? 
Could this project not use the ReID model？

**Comment by mikel-brostrom** [comment]
You have that information in the README: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html
