### ISSUE TITLE
boxmot/tracker_zoo.py

### ISSUE THREAD

**Issue by Hunter-v1** [mikel-brostrom/yolov8_tracking#896]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar enhancement requests.

### Description

https://github.com/mikel-brostrom/yolov8_tracking/blob/2a59651e0c7230940e84dc769e1aa9f57b8f48d9/boxmot/tracker_zoo.py#L80
it should be `deepocsort = OCSort`
https://github.com/mikel-brostrom/yolov8_tracking/blob/2a59651e0c7230940e84dc769e1aa9f57b8f48d9/boxmot/tracker_zoo.py#L92
it should be `return deepocsort `

**Comment by mikel-brostrom** [comment]
Thx for reporting this typo! Fixed!
